### ISSUE TITLE
Changing the interface language

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#497] opened 2020-07-23 10:49 UTC
Suggestion.
Please add an item to **Kiwix** (.appimg) to change the interface language.
You can add the item for changing the interface language to the drop down list by clicking the button with **three dots**:
![Add-lang-support](https://user-images.githubusercontent.com/65112331/88277613-af606d80-cce9-11ea-9c14-a3788e0bad03.gif)

This way the user can choose the interface language from all available languages:
![kiwix-2-0-3-translations](https://user-images.githubusercontent.com/65112331/88278291-ceabca80-ccea-11ea-9293-709480da8550.png)

PS: please tell on which page the Kiwix interface is translated?

**Comment by kelson42** [comment] 2020-07-24 07:28
This is a duplicate of #478. Everyboday can translate Kiwix' softwares on https://translate.kiwix.org

**Closed by kelson42** 2020-07-24 07:28 UTC
Labels: Qt, UI, duplicate, enhancement, good first issue, i18n
