### ISSUE TITLE
"The requested URL can not be loaded because service workers are not supported here" for zim from zimit.kiwix.org

### ISSUE THREAD

**Issue by vitaly-zdanevich** [kiwix/kiwix-desktop#1133] opened 2024-06-19 22:41 UTC
![2024-jun-20--02-40-22_maim](https://github.com/kiwix/kiwix-desktop/assets/3514015/8f387592-a588-41d6-9c78-df1adb2d7ae6)

[forums.gentoo.org_716cdcf0.zip](https://github.com/user-attachments/files/15906441/forums.gentoo.org_716cdcf0.zip)

replace `zip` to `zim`.

**Comment by kelson42** [comment] 2024-06-26 11:40
@vitaly-zdanevich Thank you for your bug report. I will fix the error message. That said since 2 days we don't propose anymore this kind of ZIM files: none of our current ZIM files will require anymore the Service Workers.

**Comment by kelson42** [comment] 2024-07-30 20:00
This is a known issue with Zimit1 ZIM files which were not able to load everywhere properly because of the service worker. In the mean time, we have launche Zimit2 which is not base on service workers anymore. Please redo your ZIM file with https://zimit.kiwix.org and it should be fine.

Duplicate of https://github.com/kiwix/kiwix-desktop/issues/487

**Closed by kelson42** 2024-07-30 20:00 UTC
Labels: bug, question
