### ISSUE TITLE
Bug: Appimage does not boot on Ubuntu

### ISSUE THREAD

**Issue by jl2359** [kiwix/kiwix-desktop#609] opened 2021-03-06 21:40 UTC
kiwix-desktop_x86_64_2.0.5.appimage does not boot on 64-bit Ubuntu 20.04.2 LTS

**Comment by kelson42** [comment] 2021-03-07 14:10
This is a duplicate of https://github.com/kiwix/kiwix-desktop/issues/486#issuecomment-684781183

**Closed by kelson42** 2021-03-07 14:10 UTC
Labels: question
