### ISSUE TITLE
Kiwix Desktop Windows - The "All files" section is empty

### ISSUE THREAD

**Issue by micha06de** [kiwix/kiwix-desktop#708] opened 2021-10-27 09:09 UTC
The "All files" section is empty, no content can be browsed (all filters are set to "all"). When clicking on "All Files", the blue circle of the progress indicator flashes briefly, then an empty list is displayed.
How can the problem be fixed?

**Comment by kelson42** [comment] 2021-10-31 06:26
@micha06de Any news?

**Comment by tehseano** [comment] 2021-11-11 00:13
Also curious about this, the list is completely blank for me. I thought It was my pi-hole but, disabling that and pull it off network still yields a blank screen. Just spent the last 30 minutes trying to figure out how to download files and everything keeps saying "its in the app" but nothing in the app tells me its not loading a list. I thought it was just looking at local files and that's it.

**Comment by kelson42** [comment] 2021-11-11 02:33
@tehseano If you start kiwix-desktop from the command line do you see any debug/error message?

**Comment by tehseano** [comment] 2021-11-11 02:48
Is there a command line argument I'm supposed to launch it with? I'm guessing this isn't what you wanted me to do, but if so, no it did not.

![kiwix_blank](https://user-images.githubusercontent.com/37715910/141228257-3151bb81-be59-4c1a-b3a0-3f7d18cbd19d.png)

**Comment by kelson42** [comment] 2021-11-11 04:02
@mgautierfr I guess at this stage this is more a question for you. If something fails, which seems to be case here, we shiuld have some way to see it in the STDOUT/STDERR.

**Comment by kelson42** [comment] 2021-11-11 06:37
@tehseano It is quit obvious that you have no language or category filter configured in the left sidebar, you confirm?

**Comment by tehseano** [comment] 2021-11-11 14:50
> @tehseano It is quit obvious that you have no language or category filter configured in the left sidebar, you confirm?

Correct they are just set to their defaults for "all". Selecting a category or language does not have any effect.

![Screenshot_2](https://user-images.githubusercontent.com/37715910/141318241-2f957715-f819-431d-a968-30f78ac8b15e.png)

**Comment by ImportTaste** [comment] 2022-02-25 02:38
> @micha06de Would you be able please to test the latest test version https://download.kiwix.org/nightly/2021-10-28/kiwix-hotspot-win64.exe ? I strongly suspect your computer / network somehow block the requests to our online catalogue.

Isn't this different software? Kiwix Desktop is different from Kiwix Hotspot. As far as I can tell, there is no nightly build for Kiwix Desktop for Windows.

**Comment by kelson42** [comment] 2022-02-25 14:19
Pretty sure this is a duplicate of #785. Shiukd work with a recent nigjtly http://download.kiwix.org/nightly/2022-02-24/

**Closed by kelson42** 2022-02-25 14:19 UTC
Labels: question
