### ISSUE TITLE
Tab graphic bug

### ISSUE THREAD

**Issue by gmikhail** [kiwix/kiwix-desktop#912] opened 2022-12-26 20:25 UTC
Unnecessary tab separator is displayed when opening a new tab:

![](https://i.imgur.com/EUgc8Bw.png)

And when you close tab it disappears:

![](https://i.imgur.com/sWbJZv8.png)

I also think that opening a blank tab with no content is itself a bug. At least I did not find how to interact with it (search doesn't work on it).

Version: 2.3.1
Windows 10 Pro 22H2 (build 19045.2364)

**Comment by kelson42** [comment] 2022-12-28 08:40
@gmikhail If you run `kiwix-serve.exe —version`, what is printed?

**Comment by gmikhail** [comment] 2022-12-28 08:50
@kelson42 I don't have this file. `kiwix-desktop.exe` does not find this command. The installer was downloaded from the official website: https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64.zip (redirect to https://mirrors.dotsrc.org/kiwix/release/kiwix-desktop/kiwix-desktop_windows_x64_2.3.1.zip)

**Comment by kelson42** [comment] 2022-12-28 09:09
@gmikhail Ok, sorry might be kiwix.exe, but will check myself.

**Comment by kelson42** [comment] 2023-04-27 13:45
@juuz0 Are you able to reproduce this issue?

**Comment by goutnet** [comment] 2023-05-14 15:49
Hi @kelson42 I gave it a try on last master (but can't repro):

![image](https://github.com/kiwix/kiwix-desktop/assets/3543067/31084d3b-f0c3-41c2-8acd-f22fb7ad489e)

@gmikhail could you maybe provide more specific instructions to reproduce this issue?

**Comment by gmikhail** [comment] 2023-05-14 16:42
Hi @goutnet 

Latest version from the official website still has this problem (download link redirect to https://ftp.fau.de/kiwix/release/kiwix-desktop/kiwix-desktop_windows_x64_2.3.1-2.zip).

Judging by window appearance, you are using Linux, while I am using the Windows version. Maybe it's a Windows-specific Qt thing? Because arrows for switching tabs on overflow is also different.

![GIF](https://github.com/kiwix/kiwix-desktop/assets/4838367/8bd206a0-598c-4b0b-af2d-49899ce6557e)

Unfortunately, I do not currently have the opportunity to compile Kiwix from source to check if there is a bug.

Also in your screenshot you can see that you can open several empty tabs. Which in itself is also wrong behavior because an empty tab cannot be interacted with (I mentioned about this in the first message).

**Comment by goutnet** [comment] 2023-05-14 17:41
correct, I am using Linux indeed. I don't have a Windows env running just now (will set it up later).

Regarding the empty tabs though, that one I confirm I can see it on Linux. @kelson42  is this a bug or a feature? (aka: should empty tabs be allowed?), let me know :)

**Comment by kelson42** [comment] 2023-05-15 04:40
Empty tab clicking on + is « normal ». Feature is not fully implemented (it’s a duplicate of https://github.com/kiwix/kiwix-desktop/issues/499).

The problem is only the visible surnumerous bar. If not bug by us, the sounds like an upstream bug which should be reported/identified.

**Comment by kelson42** [comment] 2023-08-11 19:04
> The problem is only the visible surnumerous vertical bar. If not buggy by us, this sounds like an upstream bug which should be reported/identified.

I strongly suspect here a bug with Qt 5.13 used in the built, here (on my dev system) with Qt 5.15 I don't have the problem. We will wait to update the version Qt to see if we still have this problem. It's not important enough IMO to invest more time for the moment.

**Closed** 2024-03-04 07:20 UTC
Labels: bug, good first issue

**Comment by juuz0** [comment] 2024-09-09 16:43
@kelson42 imo this still exists (and also unnecessary thickness on top of tabs) - on latest app image.
![image](https://github.com/user-attachments/assets/fee7c3dd-d3b4-4d3e-b8a6-aac378d9073c)

Pretty simple fix though, just make border-right and border-top 0 for tabbar (but let me know if you can reproduce)

**Comment by juuz0** [comment] 2024-09-09 16:59
@kelson42 5.15 but should it matter on an appimage?
