### ISSUE TITLE
Cities Location dont show in article maps in German zim-file

### ISSUE THREAD

**Issue by gcast20** [kiwix/kiwix-desktop#546] opened 2020-12-02 21:38 UTC
Zim-File: wikipedia_de_all_maxi.zim (current version from 2020-11)
Kiwix-Desktop: 2.0.3 (build date: Thu 07/02/2020)
Finding: look up the article for e.g., Madrid or Paris - the location of the city does not show up on the map near the top of the article. At certain specific, rather high zoom levels a red ring does show up, however.

**Comment by kelson42** [comment] 2020-12-03 08:05
@gcast20 I guess you mean the coordinates at the top right? I confirm they are missing. The offline version is based on the mobile version of Wikipedia which does not provide them, see https://de.m.wikipedia.org/wiki/Paris.

**Comment by gcast20** [comment] 2020-12-03 09:01
@kelson42 yes, the coordinates at the top right.. The original mobile wikipedia, to me, looks ok - the red dot shows, there, where Paris is. The offline version does have something at that place, though: by zooming in sufficiently (see attachment) one can see that something that looks like a miniature scroll bar is covering the red dot. On playing with the zoom level (Ctrl+Mouse Wheel), there are positions where the red dot becomes fully visible, just not in the default zoom level.
![kiwix-German-wiki-article_Map_Paris](https://user-images.githubusercontent.com/42801235/100987221-85983c80-354e-11eb-84b0-0ef11e4d074e.png)

**Comment by kelson42** [comment] 2020-12-03 09:13
OK, I get it: the red dot is somehow not displaying properly.

**Comment by kelson42** [comment] 2024-05-22 18:06
Should be move to openzim/mwoffliner.

**Comment by kelson42** [comment] 2024-05-22 18:07
Duplicate of https://github.com/openzim/mwoffliner/issues/1953

**Closed by kelson42** 2024-05-22 18:07 UTC
Labels: bug, question
