### ISSUE TITLE
Bad response and keyboard experience

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#395] opened 2020-04-06 13:06 UTC
(Initially open by @ynikitenko on flathub/org.kiwix.desktop#5)

I installed the recent version using flatpak install flathub org.kiwix.desktop (in fact the problem was present in my previous installation as well).
When I used Kiwix several years ago, it required me to choose the zim library (I couldn't use two simultaneously). Then I could type Ctrl+L as in a browser and type the word I wanted to find.
Now Ctrl+L doesn't work in the application. I have to draw the cursor to the search bar and activate that.
In the settings I don't have any shortcut for searchbar.

But this is not the only problem. When I type, for example, user in the search bar (I loaded wiktionary), below that appear several suggestions (the first one being userer). When I type user and press Enter, userer is opened, which is not appropriate.
Pretty often, even when I press user with mouse from the suggestion list, it doesn't open the article. I have to close Kiwix and open that again, and then it works.

I'm not sure whether it is connected to the flathub version. I tried to install from source, but failed yet. If there is really some core limitation in the flathub version, please write about that in its README.

I'm using Gnome desktop on Fedora Core 29.

**Comment by kelson42** [comment] 2020-04-09 10:45
@ynikitenko Thank you for your report. First of all, it would be great to confirm that these problem still occur with 2.0 we just have released, and then we should split that tickets in smaller one as your report many different things.

**Comment by ynikitenko** [comment] 2020-04-09 10:59
Thank you. If you have the new version compiled, would you mind checking that?

**Comment by kelson42** [comment] 2020-04-24 10:15
>  Then I could type Ctrl+L as in a browser and type the word I wanted to find.
> Now Ctrl+L doesn't work in the application. I have to draw the cursor to the search bar and activate that.

Thx for reporting this. Handled with #426.

**Comment by kelson42** [comment] 2020-04-24 10:19
> But this is not the only problem. When I type, for example, user in the search bar (I loaded wiktionary), below that appear several suggestions (the first one being userer). When I type user and press Enter, userer is opened, which is not appropriate.

@ynikitenko I think this has been fixed in 2.0.1. Could you please confirm this works for you?

**Comment by ynikitenko** [comment] 2020-04-24 10:34
@kelson42 this is great, thank you! I'll check it. This is a really necessary feature for me. 
I posted another problem in https://wiki.kiwix.org/wiki/Talk:Content_in_all_languages - there are problems with Zim files, words translations are missing. Where should I report that?

**Comment by ynikitenko** [comment] 2020-04-24 11:31
So, I installed the recent 2.0.1 version from flathub. 
The Ctrl+L shortcut really works, which is great. But it has these issues:
- when I open a new tab (Ctrl+T), old text remains there. From there, only fulltext search is available.
- again, when I type 'love' in the search bar, the word 'loved' is suggested (I don't know why). But when I type Enter, not even 'loved' is chosen, but fulltext search of 'love'! It must be much easier just to open the word if it exists.

Please check it yourself. It's some basic work with articles. 

When I have several tabs, search stops working. I add screenshots.

What I think is necessary is: 
- clear (or select all) the search field when opening another tab or when activating the search bar. Just do it as in a browser. Ctrl+L should select the existing text.
- make exact word result the default (not fulltext search, if the article exists, and not an article with a longer name!)
- fix 'file not found' error. 

It seems I can't attach screenshots here, so I posted them on my [google drive](https://drive.google.com/drive/folders/1pR_hRwNEEOYd-9U56H11xgTOpNjJjHvi?usp=sharing).

**Comment by ynikitenko** [comment] 2020-04-24 11:37
And after some work (navigate several different articles with a mouse) Ctrl+L stops working at all. :( At least on that same tab. On a new tab it works again.

**Comment by kelson42** [comment] 2020-04-24 11:42
@ynikitenko Please open one ticket per issue. Otherwise this is really difficult to handle.

**Comment by ynikitenko** [comment] 2020-04-24 11:47
@kelson42 should the first issue "clear (or select all) the search field when opening another tab or when activating the search bar. Just do it as in a browser. Ctrl+L should select the existing text."
be left as it is? Seems there are two issues already on that.

Would you mind opening these issues yourself? I'd really not like to install complete new software each time any of them is updated. For you it must be easier.

**Comment by ynikitenko** [comment] 2020-04-24 11:47
@kelson42 where would you recommend to open an issue on Zim files? (missing or not shown translations)

**Comment by kelson42** [comment] 2020-04-24 11:49
>     * when I open a new tab (Ctrl+T), old text remains there. From there, only fulltext search is available.

I confirm, handled in  #428

**Comment by kelson42** [comment] 2020-04-24 11:52
>     * again, when I type 'love' in the search bar, the word 'loved' is suggested (I don't know why). But when I type Enter, not even 'loved' is chosen, but fulltext search of 'love'! It must be much easier just to open the word if it exists.

This is exactly how it works with 2.0.1 and Wiktionary EN nopic of 2020-03. I can not reproduce the problem you report.

**Comment by kelson42** [comment] 2020-04-24 11:54
> When I have several tabs, search stops working. I add screenshots.

I can not reproduce that problem either, here I need a clear and detailed reproduction steps I believe.

**Comment by kelson42** [comment] 2020-04-24 11:59
>     * clear (or select all) the search field when opening another tab or when activating the search bar. Just do it as in a browser. Ctrl+L should select the existing text.

Agree, see #428

>     * make exact word result the default (not fulltext search, if the article exists, and not an article with a longer name!)

This is how it works for me, waiting for a detailed reprocase.
 
>     * fix 'file not found' error.

At least for new tab, this is #428

> It seems I can't attach screenshots here, so I posted them on my [google drive](https://drive.google.com/drive/folders/1pR_hRwNEEOYd-9U56H11xgTOpNjJjHvi?usp=sharing).

You should be able, don't know what you do, but you have a link to click under each comment box.

**Comment by kelson42** [comment] 2020-04-24 12:00
> @kelson42 where would you recommend to open an issue on Zim files? (missing or not shown translations)

In the proper scraper (depending of the zim file). See https://github.com/openzim/

**Comment by kelson42** [comment] 2020-04-24 12:00
Closing this ticket as this is a moving target and reported problems which are clear handle in other tickets.

**Closed by kelson42** 2020-04-24 12:00 UTC
Labels: bug, question, search

**Comment by ynikitenko** [comment] 2020-04-24 12:30
OK, great that you linked to other tickets.
I'll write a detailed description.

**Comment by ynikitenko** [comment] 2020-04-24 12:31
But there is another issue that Ctrl stops working in the current tab. Where is its ticket?
