### ISSUE TITLE
Does Kiwix uses more memory as Chrome?

### ISSUE THREAD

**Issue by y1111** [kiwix/kiwix-desktop#1296] opened 2024-12-20 17:58 UTC
i expected more efficient like a pdf reader or notepad . but this app takes 100-200mb per page it opens , with 2-4 tbas its already more than a GB
for compare thats how much chromium or ff browsers take per tab in wikipedia , but its also full featured browser much more complex.
and the browser even have the task managers in with i can select and kill some tabs to release ram
for compare too , in simple "links graphics" browser (without js) it takes a mere ~10-15mb per tab (the same pages) (with images)

**Comment by kelson42** [comment] 2024-12-20 19:36
Considering that at the core, it works exactly like a browser... not a surprise the meomery consumption is the same. All of this is manage by Qt anyway, we have no way to control much memory usage there.

**Comment by y1111** [comment] 2024-12-20 20:30
can this browser that qt make be configured ? like disable js ? this probalby would make it smaleer and faster.
i just oipened to see in k-meleon browser - simpler but it have js and its enable . and from opening at 80-85mb it goes only to 95-99mb so about 20mb more for the wioki page, and with js enabled (i even open 2 more pages and only 20-30mb more in ram)

**Comment by y1111** [comment] 2024-12-20 20:54
and it seems it doesnt even release the memory back when closing tabs . i just looked the app is still opened here in backgroundand just checked in taskmngr it takes 800MB , just with 2 tiny tabs barely 1 image.

then i click in some link open 3 tabs total 5 tabs only it takes 1166MB .
look even comparing to browsers , opera is opened with some 50-70 tabs taskmgr show 43 processes an this all taking only 1882MB
(also opera have some 30-40 separeta processes half less 10mb and some 10-50 3 200~mb . so lets say a GB more even 3GB for ~60tabs) 
really inefficient, not scaling well

**Comment by y1111** [comment] 2024-12-20 21:11
i see here https://github.com/kiwix/kiwix-desktop/issues/1244#issuecomment-2473133877 u say will move to qt6 . will this make it more efficient is this memory use ? 
and the app is lika a browser made in qt , is it ? any links or how it works and details . to help me or newbies wanting to contribute to understand faster

**Comment by kelson42** [comment] 2024-12-21 07:56
All of this is handled by https://wiki.qt.io/QtWebEngine, which is basicaly a Chromium in Qt. I don't think moving tomQt6 will change anything fundamental. This is so intricated in Qt that we can not change this. Closing this issue, are I see nothing which can be done.

**Comment by veloman-yunkan** [comment] 2024-12-22 09:44
> All of this is handled by https://wiki.qt.io/QtWebEngine, which is basicaly a Chromium in Qt. I don't think moving tomQt6 will change anything fundamental. This is so intricated in Qt that we can not change this. Closing this issue, are I see nothing which can be done.

@kelson42 I don't think that such tickets should be closed based on pure guesswork without actually investigating whether there is a problem that is in our area of responsibility.

**Comment by kelson42** [comment] 2024-12-22 09:47
@veloman-yunkan To make an investigation somthing should be clearly buggy... or at least suspicious. I see nothing in this report which let me think something does not work as expected. Do you?

**Comment by veloman-yunkan** [comment] 2024-12-22 09:58
@kelson42 

> and it seems it doesnt even release the memory back when closing tabs

This may be wrong assessment, but at least it has to be looked into.

**Comment by kelson42** [comment] 2024-12-22 10:20
> A clear comparison with Chromium showing that for the same content, the memory consumption is widely higher would be such of a clear hint for example that something is wrong.

@y1111 Would you be able please to provide such a benchmark with all the details so a dev could try to reproduce it (when something is clearly wrong)?

**Comment by kelson42** [comment] 2024-12-26 15:41
@veloman-yunkan I finally made a rough memory usage analysis to - at least - verify there is not a massive memory mgmt problem.

To compare both `chromium` (snap version) and `kiwix`, I have run each of them with the approximatively the same content. Chromium loading the article online and Kiwix loading the article from the ZIM snapshot. I have then compared the whole `RES` memory usage using `htop` (I have removed the threads with `ctrl+h` and then add the memory used by each process. Do to that I have filtered the Chromium processes using `htop --filter="chrome --type=renderer"`.

Here are the results:

3 tabs open:
* Kiwix; 739 MB
* Chromium: 629 MB

6 tabs open:
* Kiwix: 1037 MB
* Chromium: 1031 MB

It's important to not take these results as a scientific measurements, they are too many caveats in the protocol experimentation. That said I believe that if we tolerate an error margin of around 150MB this results should be trustable.

I have also looked how behaves the memory once we start to close the tabs... and it is true that the memory does not 100% come back with Kiwix, whereas it does on Chrome. I believe this is because on Chromium you have basically one clear process per tab open, so once the tab is close the memory is 100% freed because the process is closed. Kiwix renderer does not work like this and does not have one process per tab...  but that does not mean that the memory consume keeps growing when you open new tabs... so I see no problem.

To conclude, to me:
* The memory usage on Kiwix is not fundamentaly different on Kiwix than on Chromium
* I see no fundamental problem around memory mgmt when tabs are closed on Kiwix

**Closed by kelson42** 2024-12-26 15:41 UTC
Labels: question
