### ISSUE TITLE
Kiwix from ppa crashes on Ubuntu 20.04

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#524] opened 2020-10-01 12:21 UTC
When I try to open a zim (Wikipedia from 2018), kiwix crashes with this error:
```
$ kiwix-desktop 
Library directory : "/home/cyrille/.local/share/kiwix"
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
add widget
Erreur de segmentation
```

**Comment by kelson42** [comment] 2020-10-01 12:25
@LAfricain We publish thousands of Wikipedia ZIM files per month, this is not specific enough. Is that file still online? If "yes" what is the URL?

**Comment by LAfricain** [comment] 2020-10-01 12:27
No it's not online, but I have the same issue with my other "old" wiki. May I try with an new wiki?

**Comment by kelson42** [comment] 2020-10-01 12:28
@LAfricain Please try with a new ZIM file. If it work with a new ZIM file then I will ask you to upload one of the problematic file somewhere online, otherwise we won't be able to do anything.

**Comment by LAfricain** [comment] 2020-10-02 07:09
I download wikiquote and it's not working, with a new zim kiwix crashes too.

**Comment by kelson42** [comment] 2020-10-02 07:21
@legoktm I confirm the behaviour with the `dev` PPA, one reproduction case:
```
$ kiwix-desktop /home/kelson/Downloads/wikipedia_en_all_maxi_2020-09.zim 
Library directory : "/home/kelson/.local/share/kiwix"
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
add widget
Segmentation fault (core dumped)
```

Does not happen at all with git master compiled locally

**Comment by kelson42** [comment] 2020-10-02 07:25
PPA kiwix-serve seems to work well, so probably not related to libkiwix/libzim.

**Comment by kelson42** [comment] 2020-10-02 07:29
@mgautierfr This is the backtrace
```
(gdb) bt
#0  0x00005579fa9d5056 in ?? ()
#1  0x00005579fa9d9bd1 in ?? ()
#2  0x00005579fa9dbf27 in ?? ()
#3  0x00007f61ae8af57f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#4  0x00007f61ae8addf6 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#5  0x00007f61b0500fc0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#6  0x00007f61b0521ae1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#7  0x00007f61b0522803 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#8  0x00007f61b052297d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#9  0x00007f61ae8687fb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#10 0x00007f61acf7dcf5 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f61adb4fa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007f61adb590f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f61acf5193a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f61acf545b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f61acfa9f67 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f61a8478fbd in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f61a8479240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f61a84792e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f61acfa9565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f61acf504db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f61acf58246 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00005579fa9bf1e5 in ?? ()
#23 0x00007f61ac8df0b3 in __libc_start_main (main=0x5579fa9bf060, argc=2, argv=0x7ffd08b3af48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd08b3af38) at ../csu/libc-start.c:308
#24 0x00005579fa9bfc8e in ?? ()
```

**Comment by mgautierfr** [comment] 2020-10-02 15:29
The crash is on Qt side, but it is not possible to tell the root cause for now.
I see no frame related to kiwix-desktop in the backtrace. And a locally compiled kiwix-desktop (with same Qt version) work.

**Comment by kelson42** [comment] 2020-10-03 13:20
@mgautierfr Thank you for the test with the same version of Qt, this one might not be trivial to fix.... ;(

**Comment by LAfricain** [comment] 2020-10-07 10:55
Hi, 
I just pushed kiwix for focal (the same as for 18.04) on my ppa. It's working well.

**Comment by kelson42** [comment] 2020-11-21 16:23
@LAfricain I can not reproduce the problem with the latest 2.0.5 release. Would you be able to check again on your side please?

**Comment by kelson42** [comment] 2020-11-23 09:24
@LAfricain Closing, feel free to reopen it if the problem is not solved on your end. Thx for the bug report.

**Closed by kelson42** 2020-11-23 09:24 UTC
Labels: Linux, bug

**Comment by LAfricain** [comment] 2020-11-23 18:14
Yes it's working! Thank you!

**Comment by LAfricain** [comment] 2021-11-26 19:49
New install, on Ubuntu 20.04 Mate, new crash...

**Comment by legoktm** [comment] 2021-11-26 20:05
@LAfricain can you file a new task with more details? I'm guessing it's crashing for a different reason this time.

**Comment by kelson42** [comment] 2021-11-26 20:05
@LAfricain Can you please open a new ticket and give the details?

**Comment by LAfricain** [comment] 2021-11-30 15:55
Hello,
The new bug report : #734
