### ISSUE TITLE
Doesn't remember a file

### ISSUE THREAD

**Issue by mohmad-null** [kiwix/kiwix-desktop#293] opened 2019-11-08 09:06 UTC
2.0, windows. I add a file, do my stuff (well try to, 2.0 is unusable), close it, and re-open 2.0.
It doesn't remember the file.

**Comment by mohmad-null** [comment] 2019-11-08 09:07
Nor does it even remember which directory I was in previously

**Comment by kelson42** [comment] 2019-11-08 10:56
> Nor does it even remember which directory I was in previously

What do you mean exactly with "directory"? Do you have a step-by-step procedure explaining what you mean?

**Comment by jetownfeve21** [comment] 2019-11-08 10:56
@mohmad-null Can you give us the specific file you used to allow us to better understand what happened

**Comment by kelson42** [comment] 2019-11-18 03:18
@mohmad-null Without your help to better understanf your bug report, I will close this ticket.

**Comment by kelson42** [comment] 2019-11-20 14:28
@mohmad-null No feedback, so I close the ticket. Might be a duplicate of #300, who knows!

**Closed by kelson42** 2019-11-20 14:28 UTC
Labels: bug, question
