### ISSUE TITLE
Kiwix User Interface problems

### ISSUE THREAD

**Issue by InettaFund** [kiwix/kiwix-desktop#238] opened 2019-08-27 19:28 UTC
I am trying to prepare a USB drive that can be used completely offline by students that do not have access to the Internet. I have encountered a couple of issues that I hope you will be able to help me correct.  Stephane and I are proposing to use this USB drive in a proposal to Motorola assuming I can get buy-in from rural school teachers and administrators, which the USB is designed to allow them to evaluate.

I downloaded and installed the Kiwix desktop software on the USB drive in a directory named D:\kiwix-desktop_windows_x64_2.0-rc1, next I downloaded to the USB
the following English language content and placed them into a directory named 'content'.
wikipedia_en_chemistry_novid_2019-05.zim, 
wikipedia_en_for-schools_2018-09.zim, 
wikipedia_en_geography_novid_2019-05.zim, 
wikipedia_en_history_novid_2019-06.zim,  
wikipedia_en_mathematics_novid_2019-05.zim,  
wikipedia_en_mathematics_novid_2019-05.zim, 
wikipedia_en_medicine_novid_2018-10.zim, 
wikipedia_en_molcell_novid_2018-10.zim, 
wikipedia_en_physics_novid_2019-05.zim

I cannot get the Kiwix desktop software to display any of these files underLocal Files  or any of the other file display options, including All. In order to get any of the content to display I have to manually load each using the file menu. Only 6 of these .zim files can be opened at a time it appears and the name of the content (e.g. Mathematics) does not display in the heading but instead a .zim file name which the user cannot determine what it is without clicking to display. 
Ideally, once the Kiwix desktop is launched all of the .zim content would be shown under Local files so students only have to click the one they want to open, and the name of the content would display instead of a .zim file name.
I would appreciate any help you can give me in getting these issues addressed.  As a non profit, my budget is low but **I am willing to make a contribution to an analyst willing to work with me and help me to solve these Kiwix UI issues.**

**Comment by kelson42** [comment] 2019-08-28 06:41
Thank you for your ticket, this is a duplicate of #136

**Closed by kelson42** 2019-08-28 06:41 UTC
