### ISSUE TITLE
Cannot open musictheory.net_en_all_2022-06.zim in Kiwix Desktop

### ISSUE THREAD

**Issue by lsolesen** [kiwix/kiwix-desktop#938] opened 2023-05-01 09:06 UTC
When trying to open 'musictheory.net_en_all_2022-06.zim' in Kiwix Desktop, I get the following error.

<img width="953" alt="kiwix-desktop_RLIGtoyp0G" src="https://user-images.githubusercontent.com/148026/235432562-7eddc1a0-49d2-4732-8b9d-8222328e8198.png">

Same happens with 'open_street_maps_2023-03.zim'. Both are just downloaded from the Kiwix Content page. It does not happen however with the other packages, I have downloaded, e.g. 'phet_en_2023-01.zim'.

When opening the same files on my Android Kiwix, they both work fine, so the problems is only in Kiwix Desktop for Windows. Version 2.3.1 on Windows 11.

**Comment by mgautierfr** [comment] 2023-05-02 08:46
Duplicate of https://github.com/kiwix/kiwix-desktop/issues/487

**Closed by mgautierfr** 2023-05-02 08:46 UTC
Labels: question
