### ISSUE TITLE
kiwix flatpak depends on outdated runtimes/extensions

### ISSUE THREAD

**Issue by VorpalBlade** [kiwix/kiwix-desktop#1001] opened 2023-10-03 19:03 UTC
```console
$ flatpak update
Looking for updates…

Info: runtime org.kde.Platform branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   org.kiwix.desktop

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.kiwix.desktop

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.kiwix.desktop

Nothing to do.
```

Likely the flatpak package simply needs to be rebuilt against newer versions of the various platforms.

**Comment by kelson42** [comment] 2023-10-04 17:03
Duplicate of #961

**Closed by kelson42** 2023-10-04 17:03 UTC
Labels: duplicate, enhancement, flatpak
