### ISSUE TITLE
Confirmation alert on Windows should not show the massive Javascript code behind it

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#466] opened 2020-06-26 08:15 UTC
Window appears for instance when trying to delete a file. It is unsightly and poor UX.
![image](https://user-images.githubusercontent.com/21675885/85835783-ee0c1200-b795-11ea-91a1-677a830d7e27.png)

**Comment by kelson42** [comment] 2020-06-26 09:54
Duplicate of #421

**Closed by kelson42** 2020-06-26 09:54 UTC
Labels: enhancement
