### ISSUE TITLE
Implement feature to use "desktop-style" in kiwix-desktop application

### ISSUE THREAD

**Issue by knowledge-is-power** [kiwix/kiwix-desktop#863] opened 2022-07-14 18:29 UTC
This is related to Wikipedia zims. the article's ToC (table of contents) and template (i.e. navigation box at bottom of article) in these zims are hidden in kiwix-desktop application probably cuz the desktop app shows mobile-style by default. this hidden content can be revealed in 'kiwix PWA' or 'kiwix JS' by toggling from mobile-style to desktop-style as mentioned by @Jaifroid over [here](https://github.com/openzim/mwoffliner/issues/1597#issuecomment-1099324645)

Please implement the same feature in kiwix-desktop application as well because the desktop application MUST have desktop-style cuz it's primarily used on desktop computers!!
Thanks.

cc @kelson42 @Inbefortus @Ubuntu-2020 @Jaifroid

**Comment by Jaifroid** [comment] 2022-07-16 06:12
There are probably two issues here:

* Introduce Desktop CSS (as an option) for Kiwix Desktop -- clearly this makes a lot of sense for an app that targets desktop users;
* Display hidden navboxes -- an option to force-unhide these would be a "quick fix" and could be made available without swapping CSS for the article. It could be done as part of the JS API project.

**Comment by knowledge-is-power** [comment] 2022-08-10 02:13
@Jaifroid Hi. this issue had been open for almost a month and i dont see any progress or interest in this. i see that you are a member of kiwix organization so can you give me any update on this issue? is this issue being taken into consideration? thanks.

**Comment by kelson42** [comment] 2022-08-10 06:36
Duplicate of #42

**Closed** 2022-08-10 06:36 UTC
Labels: duplicate, enhancement

**Comment by Jaifroid** [comment] 2022-08-10 15:13
@knowledge-is-power Although I'm part of Kiwix (as a volunteer), I don't develp the Kiwix Desktop app (I don't have C++ experience), so my main focus is Kiwix JS and Kiwix JS Windows/Linux. If any Kiwix dev would like to take up the idea of force-unhiding the hidden navboxes, I'll very happily provide my experience of how it can be done.

Nevertheless, it's probably best if these kinds of Wikipedia-specific issues are dealt with by an [API in the ZIM archive](https://github.com/openzim/mwoffliner/issues/596). There was some development of a ToC with this API, but it got stalled. Perhaps any discussion should continue there.

**Comment by knowledge-is-power** [comment] 2022-08-10 17:23
#

> If any Kiwix dev would like to take up the idea of force-unhiding the hidden navboxes, I'll very happily provide my experience of how it can be done.

@kelson42 can you collaborate with @Jaifroid on this?

**Comment by kelson42** [comment] 2022-08-11 08:12
> > If any Kiwix dev would like to take up the idea of force-unhiding the hidden navboxes, I'll very happily provide my experience of how it can be done.
> 
> @kelson42 can you collaborate with @Jaifroid on this?

We collaborate all the time on Kiwix ;)
