### ISSUE TITLE
Sections collapsed in new tabs

### ISSUE THREAD

**Issue by uxelar** [kiwix/kiwix-desktop#901] opened 2022-11-05 14:29 UTC
When opening a new article in the same tab you are in, all sections are expanded. But if you open an article by right clicking a link and "Open in new tab" (or by clicking with the scroll wheel), all sections are collapsed. Shouldn't the behavior be the same, regardless of how the article is opened?

Also, an easy option to collapse/expand all sections by one single click should be added I think. This could be added in the right click menu for example.

Kiwix: kiwix-desktop_windows_x64_2.3.0
Zim: wikipedia_en_all_maxi_2022-05.zim

**Comment by kelson42** [comment] 2022-11-05 18:39
I confirm the bug, @juuz0 any clue what is going on here, looks really strange to me. I that a problem with the ZIM itself (I think there is a kind of logic inside the ZIM which uncollapse the section only if there is a certain width in the rendering zone.

**Comment by kelson42** [comment] 2022-11-05 18:40
Actually seems to be a duplicate of #690

**Comment by uxelar** [comment] 2022-11-06 10:32
I should be better at searching for old tickets before creating new ones =)

However, I still think an easy way to collapse/expand all sections should be added.
When you open a large articles with all sections expanded, it can be hard to find the information you are looking for. If the Contents-box at the top were included, this wouldn't be a problem. But without it, a collapse/expand option would help a lot.

**Closed** 2022-11-06 11:02 UTC
Labels: bug, duplicate
