### ISSUE TITLE
Not possible to open newer ZIM files with Kiwix 2.0.1-1 Win64

### ISSUE THREAD

**Issue by florian29** [kiwix/kiwix-desktop#458] opened 2020-06-04 12:48 UTC
It's not possible to open wikipedia_es_all_maxi_2020-05.zim with Kiwix Desktop for Windows x64 2.0.1-1. Even not possible to open it with the latest nightly build. This is shown when you try to open the ZIM file:
![Sin título](https://user-images.githubusercontent.com/43439672/83758133-d5ff1200-a671-11ea-93aa-1fc9f7e16da7.png)
It's not possible to perform any search or to show any article.
The ZIM file has the correct MD5 checksum.
The ZIM file can be opened without any problems with the Kiwix Firefox Addon.
It would be a good idea to check this out and publish a newer version of Kiwix Desktop for Windows x64 which can handle this ZIM file.

**Comment by florian29** [comment] 2020-06-06 10:46
I tested it with 3 different computers and I always got the same result as described above. I think this is a major bug as Spanish is one of the most important languages and it is really annoying when you download about 24 GB and can't use it. Considering all the other issues that are posted here, this one seems to me of more importance. I think someone should at least make the effort to reproduce the issue and confirm it. If it could be confirmed that this issue exist generally you should communicate us if it will be repaired or not. In the meantime I suggest to offer the older ZIM file for download instead of this one. Thank you in advance.

**Comment by kelson42** [comment] 2020-06-06 10:50
Works for me.

**Comment by kelson42** [comment] 2020-06-06 10:53
Can you load a random page (CTRL+R)?
Do you get search suggestion?
Do you get an error? on the command line if you start it manually?
Where is the path of the ZIM file? Is that an external drive?
Can you load succesfully an other file which is exactly beside it in the same directory?

**Comment by florian29** [comment] 2020-06-06 12:47
> Can you load a random page (CTRL+R)?
No, I can't load a random neither with the shortcut Ctrl+R nor by entering the Menu "Random Article". It stays with the blank page as pasted above.
> Do you get search suggestion?
No, I don't get search suggestions, only the "Fulltext search" appears but without giving any result by clicking on it.
![Sin título](https://user-images.githubusercontent.com/43439672/83944173-c57da180-a801-11ea-80b3-5544b688bbc2.png)

![Sin título1](https://user-images.githubusercontent.com/43439672/83944200-ecd46e80-a801-11ea-917e-0ada7c9f52f9.png)

> Do you get an error? on the command line if you start it manually?
If you mean starting a command box by opening cmd.exe, changing to the directory of the kiwix-desktop program, typing "kiwix-desktop" and then trying to open the ZIM file in the Kiwix Desktop program, I can't see any error in the command box.

> Where is the path of the ZIM file? Is that an external drive?
The path is "d:\diverses\Kiwix\". It's not an external drive, it's the same partition in which the kiwix-desktop program is and any other program on my computer.

> Can you load succesfully an other file which is exactly beside it in the same directory?
Yes, I can load other ZIM files and all of them are in the same directory:
![Sin título2](https://user-images.githubusercontent.com/43439672/83944395-7173bc80-a803-11ea-80f5-4d5e923b67ed.png)

All the other ZIM files (which I can open without any problem) appear in the "Library page" of the Kiwix Desktop program:

![Sin título3](https://user-images.githubusercontent.com/43439672/83944441-d3342680-a803-11ea-909d-d75d47ab058d.png)

The ZIM file which the problem is about (Wikipedia, spanish, maxi version, 2020-05 doesn't appear in this library page, even after trying to open it. (What you can see is the older version of this spanish Wikipedia ZIM from 2020-03, this opens without problems).

> What is the SHA256 of your file?
5eff3253a1cab83a8a884ba4a21a87e53b309bc9dd0af7b5753f8484bd41af8d

and the MD5 of this file is:
98c613caedd08f3cafa6dbbd54536a50
(identically to the MD5 which is published for this ZIM file)

**Comment by florian29** [comment] 2020-06-06 12:54
> Works for me but on the Linux version of Kiwix-Desktop.

That's why I think it's not a problem with the ZIM file but with the Kiwix-Dektop program for windows. As I mentioned above the ZIM file works for me with the Firefox Kiwix addon (but obviously there is missing the fulltext search as a restriction of the addon). I didn't try it with the android version yet.

**Comment by florian29** [comment] 2020-06-06 13:31
> Do you get an error? on the command line if you start it manually?

Maybe it could be helpful for you if I reproce it with the latest nightly build "kiwix-desktop_windows_x64_2020-06-01" as there appears a window which shows errors and comments by opening a ZIM file. First I tried to opened the ZIM file where the problem is about. As you can see no error message appears:
![Sin título2](https://user-images.githubusercontent.com/43439672/83945334-388b1600-a80a-11ea-8f18-024de5168537.png)

To demonstrate you that it works well with other ZIM files I opened then the older version of this ZIM file (wikipedia_es_all_maxi_2020-03.zim) and the window shows some error messages but the ZIM file opens without problems:
![Sin título1](https://user-images.githubusercontent.com/43439672/83945367-75570d00-a80a-11ea-8849-bf12596a22cb.png)

**Comment by kelson42** [comment] 2020-06-07 06:56
@florian29 Thank you for your feedbacks. It seems clear that Kiwix is not able to read at all the ZIM file. The reason might be a bug in Kiwix or something related to your environnement. To me and for the moment, this is really unclear and I have no theory to validate/invalidate. What should happen here definitly is that an error should be displayed (giving a hint about what goes wrong). This is probably what we will start with, but I can not give you a timeline for the fix.

Remark: Would you be able to just make a copy in the same directory of the ZIM file (and rename it to an other random name) and see if you have the same problem? Please check the file is really readable (not sure if there is a read permission on Windows).
Remark2: An updated version of this ZIM file is currently been generated, we should test if this new one will work or not.

**Comment by kelson42** [comment] 2020-06-07 06:57
@mgautierfr Do you have an idea what could go wrong here?

**Comment by florian29** [comment] 2020-06-07 09:33
> Remark: Would you be able to just make a copy in the same directory of the ZIM file (and rename it to an other random name) and see if you have the same problem?

I had yet the same idea to rename the ZIM file and tried to open it and the result was the same (only the blank page). Now I tested it again and moved the file to another directory and renamed it and still I'm not able to open it.

> Please check the file is really readable (not sure if there is a read permission on Windows).

I checked it and the file has exactly the same permissions as any other readable ZIM file from the same directory.

**Comment by gmikhail** [comment] 2020-06-21 12:55
I confirm the problem. Kiwix 2.0.1-1 Win64 cannot open the newest wikipedia_ru_all_maxi_2020-05.zim. Everything is exactly as described above. Old wikipedia_ru_all_novid_2019-06.zim opens.

Kiwix 2.0-rc3 Win64 also can not open a new file, but shows an error:

`Cannot open D:\Programs\kiwix\wikipedia_ru_all_maxi_2020-05.zim: bad allocation`

**Comment by florian29** [comment] 2020-06-21 13:37
I've downloaded the new file "wikipedia_es_all_maxi_2020-06.zim" and tried to open it and is has the same behaviour as the old version (2020-05), only shows a blank page and there is nothing you can do. Maybe you should take a look at the code of the Kiwix Desktop program. Maybe there was something changed the way the newer ZIM files were generated. Or maybe just an incompatibility with the start page of the ZIM file. Only saying "we don't know what it is and therefore there is nothing we can do" might not be helpful for the users who want to download such a big ZIM file and cannot use it. My download volume for this month is reached at the limit, I can't download other big ZIM files anymore and I think you should care about it to solve this problem. Thank you in advance.

**Comment by florian29** [comment] 2020-06-26 12:38
> Remark2: An updated version of this ZIM file is currently been generated, we should test if this new one will work or not.
No, it doesn't (see above).

**Comment by florian29** [comment] 2020-06-26 12:56
I am not a programmer and I can't help you fixing this bug. But for general considerations it seems that there has been changed something the way the new ZIM files were created, maybe it's a kind of an "updated" ZIM version with which some ZIM file readeres (like the Linux one) can handle with, but the Windows version not.

For testing purposes I did the following: I created a file with the Windows Notepad just writing "test" inside the file and saved this file with the filename "test.zim". Obviously this isn't a valid ZIM file, but this is the idea of testing it. Then I opened the last nightly build of the Win64 Kiwix desktop and tried to open this newly created ZIM file. The result was the same as described above, when I try to open the 2020_05 or the 2020_06 spanish Wikipedia ZIM file. That is to say: there is no error message in the command box and the Kiwix desktop shows: "about:blank". What does this mean? Obviously the Kiwix desktop program cannot open the newer versions of the ZIM files, indeed it doesn't recognize them as valid ZIM files. It just doesn't try to open them and therefore it is not able to show some error message.

What can you do to fix this problem? Possibility 1: Revert the recently changes the way the ZIM files were created. (And for the future maybe it would be a good idea to test ALL the Kiwix platforms if they work with the newer ZIM files, BEFORE applying changes without the necessary tests.) Possibility 2:  Take a look in the source code of the program and fix the problem with no recognizing the newer ZIM files. Thank you in advance! Good luck!

**Comment by gmikhail** [comment] 2020-06-26 14:32
After a little investigation, I found out that the problem is in Kiwix Desktop for Windows. Because the same ZIM file opens without problems in Kiwix for Chrome.

**Workaround for everyone**
Install Kiwix extension for Chrome: https://chrome.google.com/webstore/detail/kiwix/donaljnlmapmngakoipdmehbfcioahhk/
This will allow you to open the ZIM file and work offline.

**Comment by florian29** [comment] 2020-06-26 16:43
> After a little investigation, I found out that the problem is in Kiwix Desktop for Windows. Because the same ZIM file opens without problems in Kiwix for Chrome.

The problem is indeed in Kiwix Desktop for Win64. I mentioned yet two times above that I am able to open the ZIM file with the Firefox extension.

 
> **Workaround for everyone**
> Install Kiwix extension for Chrome: https://chrome.google.com/webstore/detail/kiwix/donaljnlmapmngakoipdmehbfcioahhk/
> This will allow you to open the ZIM file and work offline.

This workaround unfortunately has the restriction that there is no fulltext search. If the problem is what I suspect, that there has been changed something in the way the newer ZIM file were created, then in a few month, when all the Wikipedia ZIM files would have been updated, the Kiwix Windows program won't be able to open no ZIM file any more. Therefore there has to be made one of the two possible solutions that I proposed above.

**Comment by kelson42** [comment] 2020-06-26 16:47
@florian29 Thx for your patience, we need to find out what goes wrong here.

**Comment by florian29** [comment] 2020-06-27 08:29
> @florian29 Thx for your patience, we need to find out what goes wrong here.

@kelson42 Thank you in advance! Hope you can fix it. I think Kiwix is a very useful project!

**Comment by florian29** [comment] 2020-06-27 08:31
I've downloaded now the new ZIM file wikipedia_de_all_maxi_2020-06.zim and the results are the same as described above: Only the blank page is showing with Kiwix Desktop for Windows, but it works with the Firefox extension for Kiwix.

**Comment by florian29** [comment] 2020-06-27 09:11
> After a little investigation, I found out that the problem is in Kiwix Desktop for Windows. Because the same ZIM file opens without problems in Kiwix for Chrome.

@gmikhail Could you please try to open an article with mathematical formulas, such as Pythagoras' theorem, please? In my case, with the Kiwix extension for Firefox it won't show the mathematical formulas anymore in the newer ZIM files (neither in the spanish nor in the german Wikipedia ZIM, both from 2020-06). With the older ZIM files (2020-03 and 2020-05 respectively) the formulas are shown correctly.

**Comment by gmikhail** [comment] 2020-06-27 09:58
@florian29 Yes, I don’t see the formulas either. Looks like the Kiwix extension render bug (perhaps formulas are stored differently than in previous versions of the ZIM file). Because if you manually save the formula as an SVG file, everything is displayed:

![Аннотация 2020-06-27 121951](https://user-images.githubusercontent.com/4838367/85919144-6562a400-b871-11ea-9523-8e05225dae23.png)

Error in the console when opening a new ZIM file:

![Аннотация 2020-06-27 125534](https://user-images.githubusercontent.com/4838367/85919612-875e2580-b875-11ea-93aa-b843200d510c.png)

Kiwix extension for Chrome 2.7.0
wikipedia_ru_all_maxi_2020-05.zim

Formulas are displayed correctly in wikipedia_ru_all_novid_2019-06.zim and there are no errors in the console.

**Comment by kelson42** [comment] 2020-06-29 17:43
It is probably a duplicate of https://github.com/openzim/libzim/issues/353

**Comment by mgautierfr** [comment] 2020-06-30 08:48
Yes, this is probably this. We don't use mmap on windows. So we were probably trying to allocate a too big memory.

Can you test with this build of kiwix-destkop : https://tmp.kiwix.org/ci/mgautier/wip_compile_windows/2020-06-30/kiwix-desktop_windows_x64_2020-06-30.zip

**Comment by florian29** [comment] 2020-06-30 09:36
> Can you test with this build of kiwix-destkop : https://tmp.kiwix.org/ci/mgautier/wip_compile_windows/2020-06-30/kiwix-desktop_windows_x64_2020-06-30.zip

@mgautierfr I confirm you that the build which you provided works! I can open now wikipedia_de_all_maxi_2020-06.zim and also wikipedia_es_all_maxi_2020-06.zim
I did a quick check with both files (opening articles with Latex based formulas, with pictures, with photos, performing a fulltext search) and everything works perfectly!
Thank you very much!!!

**Comment by kelson42** [comment] 2020-06-30 09:43
@florian29 Thx for your quick feedback. We will make an official release really soon. Closing this ticket as duplicate of https://github.com/openzim/libzim/issues/353.

**Closed by kelson42** 2020-06-30 09:43 UTC
Labels: Windows, bug
