### ISSUE TITLE
Deleting a ZIM file should move it to the trash can

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#479] opened 2020-07-06 11:10 UTC
When I delete a ZIM file from the library, it is also deleted from the hard disk at the same time! And the basket remains empty!
**Ubuntu 18.04 Unity** + **Kiwix 2.0.1-1** (*.appimage):
![Kiwix-deleting-ZIM](https://user-images.githubusercontent.com/65112331/86587366-1bc13a00-bf92-11ea-8ef6-3eb7a3e51ce0.gif)

The situation is exactly the same in the operating system **Ubuntu 18.04 MATE** + **Kiwix 2.0.1-1** (*.appimage).

**Comment by kelson42** [comment] 2020-07-06 11:20
Yes, this is a feature

**Comment by mgautierfr** [comment] 2020-07-06 15:47
We should not delete the zim file if it was not downloaded by kiwix-desktop itself (if we add it to the library because the user open a existing zim).

**Comment by kelson42** [comment] 2020-07-11 09:58
Interesting Qt ticket https://bugreports.qt.io/browse/QTBUG-47703

**Comment by kelson42** [comment] 2023-07-09 14:30
I believe that we shoudl move the ZIM file to the trash instead of just deleting it from the fs. This should at least be the configuration per default. A message at delete time should clearly tell the user that the ZIM is in the trashbox.

A settings (deactivated per default) could be done to allow to shortcut trash and immediatly delete "for ever" the file.

@juuz0 I wonder a bit of what will happen if a ZIM downloaded in the internal library via Kiwix is then restored from the trashbox. Then it won't reappear in the Kiwix library... and the user might be quite puzzle to know what to do? Do you agree? Do you have an idea to deal with that?

**Comment by kelson42** [comment] 2023-07-16 04:35
@juuz0 Any feedback?

**Comment by juuz0** [comment] 2023-07-16 21:20
> I believe that we shoudl move the ZIM file to the trash instead of just deleting it from the fs. This should at least be the configuration per default.

:white_check_mark: 

> A settings (deactivated per default) could be done to allow to shortcut trash and immediatly delete "for ever" the file.

:white_check_mark: 

> A message at delete time should clearly tell the user that the ZIM is in the trashbox.

:white_check_mark: 

> I wonder a bit of what will happen if a ZIM downloaded in the internal library via Kiwix is then restored from the trashbox.

I put the download directory into monitoring (same function as monitor directory) - so if the file is downloaded from kiwix downloader followed by moving it to trash can, if the user restores the file - it appears in Kiwix library too. Test and let me know how it works!

**Comment by kelson42** [comment] 2023-07-17 05:49
@juuz0 perfect on the principle. I though we have still a bug relazed to monitoring!? Was not sure at all it would be a good idea to alwaya monitor the download directory.

**Comment by juuz0** [comment] 2023-07-31 09:59
>  I though we have still a bug relazed to monitoring!

It was in the back of my mind that there was a bug but I can't reproduce it using the new library code. 

> With this PR, would you be able to tacle https://github.com/kiwix/kiwix-desktop/issues/517 as well?

I don't think so. I wrote a comment there about a possible way to handle just now.

**Closed** 2023-08-11 18:08 UTC
Labels: enhancement, Qt
