### ISSUE TITLE
Unable to download zim files on Kiwix 2.3.0 appimage

### ISSUE THREAD

**Issue by alrepin** [kiwix/kiwix-desktop#891] opened 2022-10-01 00:33 UTC
https://i.imgur.com/RQkd8Aw.png

**Comment by kelson42** [comment] 2022-12-04 18:02
@alrepin Difficul to say without more details, but might that be that this is a duplicate of https://github.com/kiwix/kiwix-desktop/issues/871 ?

**Comment by kelson42** [comment] 2023-08-12 08:20
Closing, as the screenshot has disappeared because not upload here on Github.

**Closed by kelson42** 2023-08-12 08:20 UTC
Labels: bug, appimage
