### ISSUE TITLE
Multiples weaknesses in library filters

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#416] opened 2020-04-15 06:54 UTC
When I open Kiwix and go to the search bar and type a zim name (e.g. "metakgp", which I know is an existing zim) no file is found.
I need to first select a language (or simply "all") for it to actually look through the catalogue and find the corresponding entries.
The normal default setting should therefore for language to be set to "all" (or better, the user's default language on their machine if that info is available) so that the first search is immediately actionable.

**Comment by kelson42** [comment] 2020-04-15 06:56
@Popolechien Which search bar do you talk about? the top one, or the one in the library?

**Comment by kelson42** [comment] 2020-04-15 06:57
@Popolechien The default language should be the one of the UI = the one of the OS in my opinion. Not "all".

**Comment by Popolechien** [comment] 2020-04-15 07:00
I'm talking about the library search bar:
![image](https://user-images.githubusercontent.com/21675885/79307616-7a2cce00-7ef7-11ea-8796-11a336c89103.png)
![image](https://user-images.githubusercontent.com/21675885/79307660-8add4400-7ef7-11ea-83b6-a7fa2c23f930.png)

**Comment by kelson42** [comment] 2020-07-04 13:28
I agree, this is not easy enough to use, but like I said the problem/solution is a bit more complex than how you describe it.

The default language is the one of the OS/UI. This is right to me. If we set "all" per default, the user will get (potentially) a lot of results which are not wanted. Don't forget most of people master only one language.

We could argue that one time the language filter has been changed it should be saved, but this is an other debate.

One other point, is that per default, Kiwix Desktop starts with the local library and not the global catalog ("All files"). So you have to switch to the online catalog as well. We could argue about that point as well.

I believe the main problem is that even if we have a language selected, we should see the other results (in particular if no result is found at all in the selected langauge). This is how Kiwix Android and Kiwix iOS work and I would like to see this here as well. Does that

**Comment by kelson42** [comment] 2022-02-15 15:49
An other problem is that the current applied filters are not displayed visibly (you should alwasy click un uncollapse and maybe even scroll).

**Comment by juuz0** [comment] 2022-02-15 17:10
For the language filters, we could start with a default (All/OS language) and similar to kiwix-serve and save the preference whenever it is changed

**Comment by kelson42** [comment] 2023-08-05 20:19
Basically a duplicate of #902

**Closed by kelson42** 2023-08-05 20:19 UTC
Labels: duplicate, enhancement, good first issue, UI
