### ISSUE TITLE
Kiwix always exiting with crash after closing it on Windows 7

### ISSUE THREAD

**Issue by BigKananga** [kiwix/kiwix-desktop#123] opened 2019-04-02 13:23 UTC
Since v2.0 alpha 4 Kiwix is always exiting with a crash when I close Kiwix. Until alpha 3 everything worked fine.
In the current version beta 4 (built 03/19/2019) the crash still exists.

OS is Win7 x64 SP1 with all updates including current C++ 2017 redistributable 14.16.27027.1 in x86 and x64.

I attach some screenshots, maybe they help.

![Unbenannt2](https://user-images.githubusercontent.com/49197621/55405702-ecd04300-555a-11e9-92f7-35c0434b826c.PNG)

![Unbenannt3](https://user-images.githubusercontent.com/49197621/55405714-f3f75100-555a-11e9-8d5c-39503e1df1c5.PNG)

**Comment by oneman123** [comment] 2019-06-12 15:45
In Beta 5 the bug still exists.

**Comment by kelson42** [comment] 2019-06-12 16:13
@BigKananga Thx you for having tested this again. We will have a look.

**Comment by BigKananga** [comment] 2019-06-21 22:37
With current build from 2019-06-14 the bug still exists. On Windows 8.1 (also with all updates) there are no crashes (also with former betas).

I noticed that there was one additional file was coming with alpha 4 (the first version where the bug appears): aria2c.exe
Maybe there is the issue?

If I can help with more information, please tell me.

**Comment by kelson42** [comment] 2019-06-22 10:55
Our problem here is that we are not able to reproduce that bug on our development computers.

**Comment by BigKananga** [comment] 2019-06-22 23:29
Yes, it is only related to Win7. I made a fresh VM win Win7 SP1 and the error still occurs.
As you can see in the screenshot, there seems to be a problem with c:\windows\system32\ntdll.dll (a Windows DLL).

I tried to replace the aria2c.exe with an older version from here to test if it works then, but no success:
https://github.com/aria2/aria2/releases?after=release-1.19.2

I could replace any file with the old ones from alpha 3 but only if I replace the kiwix-desktop.exe with the crash after closing Kiwix is gone.

I think you compile with Visual Studio 2017 (the C++ 2017 Redist is always included). Maybe you have set an option which is not compatible with Win7 SP1? Or how could I compile it by myself on Windows 7 or 8.1?

If you need more information, please tell me.
I hope you get this fixed since Win7 is still very popular.

**Comment by kelson42** [comment] 2019-06-23 05:55
@BigKananga Thank you for testing all of this. If you run kiwix-desktop.exe from the command line, do you see any message printed?

**Comment by BigKananga** [comment] 2019-06-23 10:14
You mean by typing in "kiwix-desktop.exe" in cmd? No, there isn't any message.

**Comment by kelson42** [comment] 2019-06-23 10:48
@BigKananga yes, thx.

**Comment by mgautierfr** [comment] 2019-06-24 15:26
> EDIT: i found something interesting. The crash after closing is not after the first launch of kiwix-desktop.exe. From the second launch on it crashes after closing. After restarting Windows, it's the same again, after the first launch no crash at closing, from the second launch on it crashes again after closing.

This is probably related to https://github.com/kiwix/kiwix-desktop/issues/147
The both kiwix desktop instance probably try to launch two aria instance using the same internal port.

**Comment by BigKananga** [comment] 2019-06-24 17:05
@kelson42 
Just to clarify: I don't get any additional message to the window and event log shown in first post. In CMD there isn't any message.


@mgautierfr 
In my case the instances are not running parallel but one after the other. After restarting Win7 I started the first instance of Kiwix. Then I closed it and didn't get any error message. Then I started Kiwix again, closed it and the error message appeared in a error window and in event log. If there is an issue with aria on Win7 (on 8.1 there is no problem!), then maybe aria won't be closed together with Kiwix.

**Comment by mgautierfr** [comment] 2019-06-26 08:44
> In my case the instances are not running parallel but one after the other. After restarting Win7 I started the first instance of Kiwix. Then I closed it and didn't get any error message. Then I started Kiwix again, closed it and the error message appeared in a error window and in event log. If there is an issue with aria on Win7 (on 8.1 there is no problem!), then maybe aria won't be closed together with Kiwix.

So I had misunderstood your issue. This is not related to #147.

Let clarify the behaviour :
- On win10, no crash, whatever the kiwix-desktop beta version nor if this is a first or second launch.
- On win7. The second launch of kiwix-desktop beta 4 crash. Older versions (alpha3) and first launch do not crash. 

Can you confirm ?

> After restarting Windows, it's the same again, after the first launch no crash at closing, from the second launch on it crashes again after closing.

So it is not a problem reading a configuration/zim file.

Can you check that aria2 process is correctly closed when you close kiwix ?

**Comment by BigKananga** [comment] 2019-06-26 11:56
> Let clarify the behaviour :
> 
> * On win10, no crash, whatever the kiwix-desktop beta version nor if this is a first or second launch.
> * On win7. The second launch of kiwix-desktop beta 4 crash. Older versions (alpha3) and first launch do not crash.

I tested Win8.1 instead of 10, but yes, there was no crash after closing the second launch
Regarding Win7: yes alpha 3 (the last without aria2c.exe works without any problem, every later version the first launch after restarting Windows doesn't crash when closing Kiwix, but when closing after the second launch (which is not parallel). It is really important that it crashes when closing Kiwix and not when starting Kiwix.



> Can you check that aria2 process is correctly closed when you close kiwix ?

Yes, after closing Kiwix, aria2c.exe isn't listed anymore in Taskmanager. Same when Kiwix crashed after closing.

**Comment by BigKananga** [comment] 2019-08-10 13:16
I made some new investigation with current rc1 (dated 2019-08-05) and found something interesting.

I was able to circumvent the crashes. The problem is a svchost.exe process which takes less then 1MB of RAM after the first launch. When I close it in task manager every time after exiting Kiwix, there won't be any crash after exiting the next time.

svchost has the following command:
C:\Windows\System32\svchost.exe -k WerSvcGroup

I think the process will be closed automatically after some time, but I'd have to investigate this.

Hopefully that helps you.

**Comment by kelson42** [comment] 2019-09-27 09:52
@BigKananga We just have releases the RC3 which might fix your problem. Could you please try again with https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0-rc3.zip ?

**Comment by BigKananga** [comment] 2019-09-28 13:53
@kelson42 
Unfortunately the issue still exists, now even after the first close.

**Comment by BigKananga** [comment] 2020-03-16 16:18
Unfortunately the problem still exists in RC4.

**Comment by kelson42** [comment] 2020-03-16 17:06
@BigKananga Would you be able to test against the last nightly? https://download.kiwix.org/nightly. I don't think the problem is fixed, but if it is by any chance, that would save us quite a bit of time. Thank you in advance!

**Comment by BigKananga** [comment] 2020-03-16 17:27
@kelson42 
Of course I test everything that could help you.
I tested the newest nightly from 16.03.20 and it still crashes when closing.
But there is something new, a cmd window. This is the one that crashes, not the main window.
![kiwix](https://user-images.githubusercontent.com/49197621/76784362-c7f8ce00-67b3-11ea-9106-5bd520a6bf86.PNG)

**Comment by kelson42** [comment] 2020-04-07 12:16
I reopen the ticket as I would like to get confirmation from end users. @BigKananga Would you please be able to test again with nightly in a few days (one time we have nightlies built)?

**Comment by BigKananga** [comment] 2020-04-07 12:38
@kelson42 
Of course I'll test. Next weekend?

**Comment by BigKananga** [comment] 2020-04-16 13:22
@kelson42 
I tested the last nightlys 2020-04-14 and 2020-04-15 and the crash after closing Kiwix still exists. The only improvement is the missing CMD window.

Here are some screens from crash and event log (if you need a translation please tell me):

![crash](https://user-images.githubusercontent.com/49197621/79460509-35875c80-7ff5-11ea-846a-915c66cc498c.PNG)

![crash2](https://user-images.githubusercontent.com/49197621/79460515-37512000-7ff5-11ea-82d1-74a785a9a302.PNG)

![crash3](https://user-images.githubusercontent.com/49197621/79460516-37e9b680-7ff5-11ea-98d4-4c0258d89983.PNG)

I looked at Process Explorer and I think the problem is in the kiwix-desktop.exe and not in the other started processes.

**Comment by kelson42** [comment] 2020-04-16 13:24
@BigKananga Thank you for your feedback.

**Comment by BigKananga** [comment] 2020-04-16 14:04
@kelson42 
No problem!
Additional information: all Win7 ESU updates incl. April 2020 are installed.

**Comment by BigKananga** [comment] 2020-05-03 11:57
In version 2.0.1-1 the issue still exists.

**Comment by kelson42** [comment] 2020-07-04 12:28
@BigKananga Unfortunately we still don't have tackle this problem specificaly, but a few things have been changed which might be related to that problem. This is why I have to ask you again if this still happens with last release https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0.3.zip

**Comment by BigKananga** [comment] 2020-07-07 10:38
@kelson42 
It didn't change anything, it still crashes after closing. Win7 + ESU June 2020 and current C++ Runtimes 2019.

**Comment by mjb2010** [comment] 2020-08-19 06:42
I am using kiwix-desktop_windows_x64_2.0.3.zip on Win7 and am also getting crashes upon closing the app.

It does not happen every time, and it does require using a zim file. I have 3 zim files (wiktionary_en_all_maxi_2020-07.zim, superuser.com_en_all_2020-04.zim, wikipedia_en_all_maxi_2020-06.zim), and the crash happens for all of them. In my torrent client, I re-checked the zim files and they all passed, with no corrupt pieces. The MD5s also check out.

Opening a zim file and seeing its home screen, and then closing the app without clicking on anything, does not result in a crash. I have to actually access something from deeper in the file. It does not necessarily require using the search bar; just fetching something from the file by following links from the home screen is usually sufficient.

For example, in the superuser zim, visiting the most popular article (re: cURL) does not lead to a crash, but visiting the second-most popular one (re: toaster) does.

**Comment by kelson42** [comment] 2020-08-29 15:50
Finaly, we strongly believe to have fixed this bug. It will be available in Kiwix Desktop 2.0.5 next week. Considering that meanwhile win7 has been put out of support by MS, we won’t investigate anyway if we are so unfortunate that the problem would still be there. If a similar bug impacts Win 10, then a new ticket should be open please. I would like to thank all of you for your patience and help on this one.

**Closed by kelson42** 2020-08-29 15:50 UTC
Labels: Windows, bug, question

**Comment by BigKananga** [comment] 2020-09-08 23:11
It seems that 2.0.4-1 fixed the problem. No crash so far.

A few words to Win7: you can still get updates easily until 2023. And since Kiwix is a offline application, there is nothing why not using it on Win7.

**Comment by kelson42** [comment] 2020-09-09 08:12
@BigKananga Nice to hear it works now. Only "volume license customers" get updates until 2023, see https://en.wikipedia.org/wiki/Windows_7. You can use Kiwix on Windows 7, you can even provide patches if necessary... but we don't support it anymore, which means we don't recommend to use it and we don't invest resources on it.

**Comment by mjb2010** [comment] 2020-09-25 18:47
With 2.0.4-1, the problem was resolved for me, as well. Thanks for this.
