### ISSUE TITLE
Ajax requests are refused

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-desktop#255] opened 2019-09-14 18:19 UTC
Similar to https://github.com/kiwix/kiwix-android/issues/1469 on android, XmlHttpRequest are failing in kiwix-desktop.

To be exact, those are processed (and the requested file content is received) but the `status` remains `0` ([erroneous or not sent](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status))

I've tried different approaches but none worked. To save you some digging time, here's what I tried (I might just have applied them wrong):

Setting [attributes](https://doc.qt.io/qt-5/qwebenginesettings.html#setAttribute) on [defaultSettings](https://doc.qt.io/qt-5/qwebenginesettings.html#defaultSettings). This seems to be what was needed for android.
``` c++
#include <QWebEngineSettings>
QWebEngineSettings* settings = QWebEngineSettings::defaultSettings();
settings->setAttribute(QWebEngineSettings::LocalContentCanAccessRemoteUrls, true);
settings->setAttribute(QWebEngineSettings::LocalContentCanAccessFileUrls, true);
settings->setAttribute(QWebEngineSettings::FullScreenSupportEnabled, true);
settings->setAttribute(QWebEngineSettings::PlaybackRequiresUserGesture, false);
```

Marking [zim scheme as local](https://doc.qt.io/archives/qt-5.5/qwebsecurityorigin.html#addLocalScheme). Note that this requires the `libqt5webkit5-dev` package and `QT       += webkit` in `kiwix-desktop.pro`.
``` c++
#include <QWebSecurityOrigin>
QWebSecurityOrigin::addLocalScheme("zim");
qDebug() << QWebSecurityOrigin::localSchemes();
```

Adding [security flags to the ZIM scheme](https://doc.qt.io/qt-5/qwebengineurlscheme.html#setFlags)
``` c++
QWebEngineUrlScheme scheme("zim");
scheme.setFlags(QWebEngineUrlScheme::LocalScheme);
scheme.setFlags(QWebEngineUrlScheme::SecureScheme);
scheme.setFlags(QWebEngineUrlScheme::LocalAccessAllowed);
scheme.setFlags(QWebEngineUrlScheme::ContentSecurityPolicyIgnored);
QWebEngineUrlScheme::registerScheme(scheme);
```

FYI, beside just not restricting features on ZIM, we are currently using Ajax in video-enabled ZIMs to load subtitles (from video.js). We can hack `video.js` to bypass its `status !== 0` check but it's an ugly hack.

**Comment by kelson42** [comment] 2019-09-14 18:23
@jetownfeve21 @mgautierfr This bug is quite important to me for the reasons explained by @rgaudin. Situation has been fixed in the last days with Kiwix for iOS and Kiwix for Android. Fixing Kiwix Desktop for macOS/Linux/Windows is the work still to do.

**Comment by mgautierfr** [comment] 2019-09-16 15:22
I confirm the issue. However, it seems that is it not a "security" or configuration problem.
I've open a issue on Qt side (https://bugreports.qt.io/browse/QTBUG-78316).

It seems that is because request using a custom scheme (and handler) are not real request and so, have no status code. (Or I am doing something wrong).

For now, the only workaround is to not test `status != 0`. But we will wait what Qt developers will say.

**Comment by kelson42** [comment] 2019-09-18 07:49
@mgautierfr This Kiwix-Desktop workaround should be implemented/merge ASAP. Please put a comment in the code, so we remember to check that in a few months against Qt devs.

**Comment by rgaudin** [comment] 2019-09-18 07:56
@kelson42 this is a [youtube](/openzim/youtube) side workaround.

**Comment by kelson42** [comment] 2019-09-18 07:59
@rgaudin Thx for clarification, I had a doubt after the meeting yesterday. Any reason not to implement the workaround (with proper comment in the code) on Youtube side?

**Comment by rgaudin** [comment] 2019-09-18 08:00
Nope, it's on my todo list for now-now :)
We should still keep this bug here opened to track its proper solution

**Comment by kelson42** [comment] 2019-09-24 08:41
@rgaudin @mgautierfr If not already done, don't forget to vote/watch this issue. This is the best we can do to help this Qt issue fixed.

**Comment by kelson42** [comment] 2019-09-25 19:45
The bug upstream has been closed. The fix will be available in 5.13.2 (AFAIK 5.12 branch is over and 5.12.5 is the last minor version). That said the upstream bug says that it impacts only 5.12.4, considering that we use 5.12.5 for the GNU/Linux Flathub version it would be good to confirm that 5.12.5 is not impacted (that way this would not force us to move up to 5.13).

**Comment by mgautierfr** [comment] 2019-09-26 12:50
It's me that said that it impacts 5.12.4, and it is simply because I've tested with 5.12.4.
Looking the fix commit, it really seems they add the feature to have a status code to requests on custom scheme. It doesn't look like a bug fix but as a "new feature" (probably no one use ajax on custom scheme before us).
Except if they've rewrite all their engine and forget this feature in the process, it is probably impacting all versions.

Hopefully, we should be able to compile appimage on most recent Qt once this PR https://github.com/kiwix/kiwix-build/pull/377 will be merged (and fixed)

**Comment by kelson42** [comment] 2019-10-31 15:01
Looks like we need here Qt14 (still to be released) to fix this problem.

**Comment by kelson42** [comment] 2020-01-08 16:51
Bug has been fixed in `5.13.2` and `5.14.1`.

**Comment by mgautierfr** [comment] 2020-01-09 09:04
Yes, I've seen this. However, it seems that QWebEngine is missing the last Flatpak KDE platform (https://bugs.kde.org/show_bug.cgi?id=414175).
It seems that for now the solution is to compile QWebEngine in the application flatpak but I would like to avoid this if possible.

**Comment by kelson42** [comment] 2020-01-09 09:09
@mgautierfr Yes, we have to wait here that newest version of Qt is packaged and therefore usable in appimage, Windows, flatpak.

**Comment by kelson42** [comment] 2020-04-18 13:44
I close that ticket. There is nothing more we can do here and this is basically a duplicate of https://github.com/kiwix/kiwix-build/issues/403

**Closed by kelson42** 2020-04-18 13:44 UTC
Labels: bug, question
