### ISSUE TITLE
Icons rendering on HighDPI displays

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-desktop#1244] opened 2024-11-13 10:07 UTC
Although we are using scalable (SVG) Icons, those are not rendered properly on HighDPI displays.
It's clearly visible on the _Library_ tab icon which is the Kiwix bird

![Image](https://github.com/user-attachments/assets/61e01ab7-e60f-44f2-8ad6-b48f83e6b6b2)

There are a lot of topics about this online. It seems that it [used to be complex](https://github.com/hdijkema/QtHighDpi), especially given DPR is per-display and an application can have a window in a HighDPI one and another window on a regular DPI one ; and there's the variations between the different systems and all.

I read that it [should be transparent in Qt6](https://doc.qt.io/qt-6/highdpi.html) but I haven't tested that. If someone wants to send me qt6 build I'll gladly test.

On current Qt5, I could fix the Icon with just the following… but I'm pretty sure it make the icons ugly on regular DPI

```diff
diff --git i/src/kiwixapp.cpp w/src/kiwixapp.cpp
index ed29b52..f7477b0 100644
--- i/src/kiwixapp.cpp
+++ w/src/kiwixapp.cpp
@@ -492,6 +492,7 @@ void KiwixApp::handleItemsState(TabType tabType)
     auto libraryOrSettingsTab =  (tabType == TabType::LibraryTab || tabType == TabType::SettingsTab);
     auto notBookmarkableTab = libraryOrSettingsTab || getTabWidget()->currentArticleUrl().isEmpty();
     auto app = KiwixApp::instance();
+    app->setAttribute(Qt::AA_UseHighDpiPixmaps);
     app->getAction(KiwixApp::ToggleReadingListAction)->setDisabled(libraryOrSettingsTab);
     app->getAction(KiwixApp::ToggleAddBookmarkAction)->setDisabled(notBookmarkableTab);
     app->getAction(KiwixApp::FindInPageAction)->setDisabled(libraryOrSettingsTab);

```

![Image](https://github.com/user-attachments/assets/3fc87609-378d-45f6-b8c7-b08a7e381ce8)

**Comment by kelson42** [comment] 2024-11-13 10:36
We will migrate to QT6 soon in milestone 2.4.0. Thx for the report, I will schedule the fix.

**Comment by kelson42** [comment] 2024-12-24 12:46
@BhargavMah For the moment we migrate to Qt6 then we will see if the bug still occurs.

**Comment by kelson42** [comment] 2024-12-26 22:22
It seems to work perfectly with Qt6, see here tested on Ubuntu 24.04
![Image](https://github.com/user-attachments/assets/022b7834-b54c-4455-aa49-27155b08cadd)

I will closed the issue as considered to be a duplicate of https://github.com/kiwix/kiwix-build/issues/594 (which will be fixed within a few weeks).

**Closed by kelson42** 2024-12-26 22:22 UTC
Labels: bug, good first issue
