### ISSUE TITLE
Replace vue.js HTML by native Qt (was: vue.js should not be part of the source code)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#230] opened 2019-08-16 08:26 UTC
Only our source code should be part of it. This should be downloaded at the build time.

**Comment by xurror** [comment] 2019-10-14 16:34
Do you suggest the file be removed?

**Comment by kelson42** [comment] 2019-10-14 16:45
@xurror This is not what I have written

**Comment by xurror** [comment] 2019-10-14 17:53
Oh, I think I didn't understand the issue properly

**Comment by xurror** [comment] 2019-10-16 07:01
> Only our source code should be part of it. This should be downloaded at the build time.

Please can you explain better what you mean

**Comment by kelson42** [comment] 2020-11-21 18:44
By moving the library to Qt, the problem should vanish.

**Comment by kelson42** [comment] 2020-11-28 15:05
Ticket will de facto vanish when we move the library to pure Qt.

**Comment by kelson42** [comment] 2021-08-28 09:36
Closing this ticket in favour of #665 683

**Comment by mgautierfr** [comment] 2021-08-30 10:24
> Closing this ticket in favour of #665

@kelson42 This is not a duplicate of #665 for me.

**Comment by kelson42** [comment] 2021-08-30 10:26
Where is the discrepence? Where is still used vue.js outside the library?

**Comment by kelson42** [comment] 2021-08-30 10:27
Sorry, #683

**Closed** 2021-08-31 15:03 UTC
Labels: duplicate, enhancement
