### ISSUE TITLE
.zim files not showing up in app 

### ISSUE THREAD

**Issue by JeffyJoBob** [kiwix/kiwix-desktop#1168] opened 2024-08-03 17:54 UTC
I am using a raspberry pi 5 with raspberry pi OS and KDE Plasma desktop, all the latest versions. I use the sudo apt install kiwix command to install it and download .zim files from the website and it seems to be somewhat functioning but nothing shows up in the kiwix  app display panel. I can see tabs pop up when I click on the actual .zim files but the display panel below the tabs is totally blank including Title, size, date, etc. filter tabs that appear in this window. Has anyone had this problem or found a solution to it? Thanks.

**Comment by kelson42** [comment] 2024-08-03 18:16
@JeffyJoBob This is the first time I hear about such a bug. What is your version of Kiwix (`kiwix-desktop --version`)?

**Comment by JeffyJoBob** [comment] 2024-08-03 21:15
Version 2.3.1   I might add that I have a NVME hat on my raspberry pi and that I am booting from and have Kiwix installed on that drive. Not sure if that would make any difference or not.

**Comment by kelson42** [comment] 2024-08-04 04:07
@JeffyJoBob Might that be that some of the filters is not set properly?

**Comment by JeffyJoBob** [comment] 2024-08-04 11:41
If I put Ubuntu on the same hardware setup instead of the raspberry pi os / KDE Plasma it works fine.

**Comment by kelson42** [comment] 2024-08-04 12:31
@JeffyJoBob If this is the same version of the software, then there seems to be something wrong with the packaging

**Comment by Obscure-river** [comment] 2024-08-05 01:28
Hello, i am having the same problem but on the mobile app for android devices, i downloaded the cheatography.com_en_all_2024-06.zim file from the kiwix library on my computer and copied it in to my phone external storage (exfat) in the org.kiwix.kiwixmobile file, i opened it in the app and it loaded in the reader but it was blank, it also didn't show any articles when i tried to find some in the search bar and when i tried to get to a random article the app just crashed.

**Comment by Obscure-river** [comment] 2024-08-05 07:09
As per my last comment it looks like it was just a faulty sd card in my case.

**Comment by kelson42** [comment] 2024-08-05 07:10
Closing then.

**Comment by JeffyJoBob** [comment] 2024-08-05 21:42
My original problem is still here. Nothing has been solved. I I have run this on different SD cards and tried a lot of configurations but I still have the same exact problem

**Comment by JeffyJoBob** [comment] 2024-08-05 21:45
![IMG_6873](https://github.com/user-attachments/assets/39719d98-7083-4f27-a791-27a334471799)

**Comment by kelson42** [comment] 2024-08-05 23:59
@JeffyJoBob Your screenshort show a 5 years old cersion of the software, please use latest version.

**Comment by kelson42** [comment] 2024-08-06 00:02
@JeffyJoBob Have you tried with an other content, maybe a small file from wikipedia?

**Comment by JeffyJoBob** [comment] 2024-08-06 01:05
Yes I have tried the smallest .zim I could find because I have tried to get this to work so many ways. I quit trying to do it on a nvme and have tried multiple brands of micro SD card with the OS on it. I switched to just raspberry pi os 64, fresh images that have not been modified in anyway. I’ve unplugged everything from the pi except the essentials, power, HDMI, ethernet, mouse and keyboard. as I said earlier it is a raspberry pie five and is brand new. I have moved the zoom files around to different folders, I have tried the folders listed in the settings. I have done just about everything I can think of. I’ve even made OS images on different computers and on the pi. I’m running out of things I know to try. I am no computer guru. Had no problem with it on Ubuntu.

**Comment by kelson42** [comment] 2024-08-06 05:06
Honestly, I have nomclue what is going on there, but oretty sure this is fixed in dev version. So probably better to just wait next release 2.4.0.

**Comment by JeffyJoBob** [comment] 2024-08-06 10:23
Yeah I was starting to think the same thing. Thanks for your help.

**Comment by JeffyJoBob** [comment] 2024-08-06 13:36
But I have to wonder why no one else is reporting this problem. 🤔🤔🤔

**Comment by kelson42** [comment] 2024-08-06 16:46
> But I have to wonder why no one else is reporting this problem. 🤔🤔🤔

I guess noone else use this with pios.

**Comment by BridgetteMurray** [comment] 2024-09-19 06:32
I actually have the same problem with kiwix on my Pi5 as well, I have an external ssd  and when I try and open a zim file it looks like its starting to load and then just stops and the same blank screen as you have, did you find a solution ?, all my pios has been updated and the pi restarted as running the ssd on usb3, hope you can help, thanks

**Comment by w1ld0n3** [comment] 2024-11-11 02:33
I also have the same problem on Pi5, all running on Pi micro sd card. When I try and open a zim file it looks like its starting to load and then just stops and the same blank screen as you have

**Comment by pranaysy** [comment] 2024-11-19 21:16
Quick followup: 


> A suggested fix is to set `kernel=kernel8.img` in `config.txt` on the Raspbian SD card. I am yet to try this and will update once I do.

This change worked! The issue was likely indeed with the page size incompatibility due to the newer RPi5 kernel. After setting the flag like above, I tried both the flatpak and the deb install (via `apt`) and I was able to run kiwix-desktop just like it was designed to :)


Keen to see if this works for @JeffyJoBob @w1ld0n3 and @BridgetteMurray

**Comment by w1ld0n3** [comment] 2024-11-20 18:28
> Quick followup:
> 
> > A suggested fix is to set `kernel=kernel8.img` in `config.txt` on the Raspbian SD card. I am yet to try this and will update once I do.
> 
> This change worked! The issue was likely indeed with the page size incompatibility due to the newer RPi5 kernel. After setting the flag like above, I tried both the flatpak and the deb install (via `apt`) and I was able to run kiwix-desktop just like it was designed to :)
> 
> Keen to see if this works for [@JeffyJoBob](https://github.com/JeffyJoBob) [@w1ld0n3](https://github.com/w1ld0n3) and [@BridgetteMurray](https://github.com/BridgetteMurray)

Thank you @pranaysy this change fixed the problem!

**Comment by kelson42** [comment] 2024-11-20 18:35
@pranaysy Thx a lot!

**Comment by Webserv** [comment] 2024-11-25 17:58
I didn’t report the problem because I thought that’s the way it worked. I use a browser to access the zim files by running the local kiwix web server option. I normally don’t use Kiwix on the raspberry pie, I use it on all my devices through a browser. So it never seemed like a problem.

**Comment by kelson42** [comment] 2024-11-25 18:32
I will close the issue because the problem is outside Kiwix and therefore there is nothing more we can do here. Thank you very much for explaining the issue and proposing a fix.

**Closed** 2024-11-25 18:33 UTC
Labels: bug, question
