### ISSUE TITLE
Make contents (index) table for server, extension, app

### ISSUE THREAD

**Issue by ghost** [kiwix/kiwix-desktop#600] opened 2021-02-16 12:09 UTC
I found useful extension that solves this problem for server, for Firefox.
https://addons.mozilla.org/en-US/firefox/addon/headingsmap/
It adds index, like bookmarks, which allows me to skip to any part of article, something that most or all normal wikipedia articles have. Good if you make such ability too, but for extension and app too.

**Comment by kelson42** [comment] 2021-11-28 06:31
Duplicate of #42

**Closed** 2021-11-28 06:31 UTC
Labels: duplicate, enhancement
