### ISSUE TITLE
Linux: cannot resolve EVP_PKEY_base_id, cannot resolve EVP_PKEY_base_id, or SSL_get_peer_certificate.

### ISSUE THREAD

**Issue by N0THSA** [kiwix/kiwix-desktop#947] opened 2023-06-26 01:05 UTC
#### Tried:

1. Running with and without root privileges
2. Reinstalling, restarting, and other basic troubleshooting steps
3. Connected using Ethernet and WiFi
4. Restarted computer
5. Change system time (potentially a security certificate issue)

#### Information:
The computer I am using for this is running Nobara Linux, has 500 gigabytes of space currently available, and has the system clock correct. Kiwix Desktop.

#### Expected behavior:
Clicking "all files" would show me a list of websites I can download for offline use. Instead, it showed nothing whatsoever.

#### Logs:
```
add widget
Downloading "https://library.kiwix.org:443/catalog/search?lang=eng&count=-1&notag=_sw:yes"
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
```

Any help is greatly appreciated.

**Comment by kelson42** [comment] 2023-06-26 17:25
I have transfered the ticket to Kiwix Desktop repository. The bug you have reported is valid but has already been reported. Therefore I will close it as duplicate of #871. Maybe if you try the flatpack package, it will fix the problem https://flathub.org/apps/org.kiwix.desktop.

**Comment by kelson42** [comment] 2023-06-26 17:31
@N0THSA Fedora has as well a native Kiwix package, younshould have it as well, see https://github.com/kiwix/kiwix-desktop/wiki/Repology

**Closed** 2023-06-26 17:31 UTC
Labels: bug, duplicate, question
