### ISSUE TITLE
"Unique instance" doesn't work when packaged with flatpak

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#781] opened 2022-02-02 15:51 UTC
Of fedora 34, if kiwix-desktop is installed with a rpm, when opening two zim files (by clicking on two zim files in the file browser), only one kiwix-desktop instance is launched (with two tabs).
But if kiwix-desktop is installed with a flatpak, two kiwix-desktop instances are launched.

This is probably a communication problem between the two apps as flatpak runs applications in containers.

**Comment by kelson42** [comment] 2022-02-02 17:21
Same on Ubuntu... to me looks like a regression... as AFAIK this was working.

**Comment by kelson42** [comment] 2024-12-24 12:33
Similar problem here https://github.com/ksnip/ksnip/issues/395

**Comment by kelson42** [comment] 2024-12-27 11:54
This works now. The ZIM is loaded on the pre-existing instance of Kiwix. But there is still one problem, if the Kiwix is in background then it stays in background.

**Comment by kelson42** [comment] 2024-12-27 14:55
Seems not that easy to fix https://forum.qt.io/topic/133694/using-alwaysactivatewindow-to-gain-foreground-in-win10-using-qt6-2/2

**Comment by kelson42** [comment] 2024-12-27 16:11
Closing as the problem is fixed now.

I have open a new tickets for the new problem I have discovered https://github.com/kiwix/kiwix-desktop/issues/1309

**Closed by kelson42** 2024-12-27 16:11 UTC
Labels: bug, flatpak
