### ISSUE TITLE
Search is way too slow

### ISSUE THREAD

**Issue by okkebal** [kiwix/kiwix-desktop#43] opened 2018-10-17 12:31 UTC
I use Stackoverflow zim file (2018 version)

It works: I can see pages and search works but is way too slow because:

It starts searching as soon as I type ONE Character! This is useless behaviour! It should only start to search when I have not typed any character for say 1 second. If I immediatly type antoher character... wich most people do if they type a search. So if I search for "Postman" it will

search for "p"  this takes about 20 seconds
search for "po" this takes another 10 seconds
search for "pos" this takes another 5 seconds

etc..

The keyword search takes minutes this way!

I just want it to search for "Postman" and not all the intermediate stuff

Please add a manual search button or start searching after i am done typing.

**Comment by kelson42** [comment] 2018-12-11 11:06
@okkebal I confirm, we will have to tackle that relatively quickly.

**Comment by kelson42** [comment] 2019-09-07 16:58
This has been fixed in libzim 6.0.0, will be available in rc2 (or already wavailable on Linux with flathub).

**Comment by mgautierfr** [comment] 2019-09-10 07:55
This is not fix, we still do a search for each keystroke.

**Comment by kelson42** [comment] 2019-09-10 07:58
@mgautierfr We always have made a search per keystroke. But I thought the result would be almost immediate now?! You propose to implement a kind of delay between searches?

**Comment by mgautierfr** [comment] 2019-09-10 08:06
That what the issue is about.
If we don't want, it is a `wontfix`. Not a `fixed` resolution :)

But I agree that a delay between searches is probably a good thing. There is no real need to do a search for one or two letters when the user want to search for a whole word.

**Comment by kelson42** [comment] 2019-09-10 08:09
@mgautierfr OK. We should have it for one or two letters as well. Remember the bug where "NSA" was not suggesting anything... we would have it again otherwise (for an other reason than originally).

**Comment by mgautierfr** [comment] 2019-09-10 08:26
Yes, the delay is the good solution. Simply do the search half a second after the last keystroke.

**Comment by kelson42** [comment] 2019-09-26 12:21
The root cause problem has been fixed to a large extend, I have created a ticket just to add a small delay #265.

**Closed by kelson42** 2019-09-26 12:21 UTC
Labels: bug, search

**Comment by KaKi87** [comment] 2025-02-14 00:53
Hi,
I'm experiencing this exact issue on the latest Kiwix.
Was the fix for this reverted or disabled since then ?
Thanks

**Comment by kelson42** [comment] 2025-02-14 16:16
@KaKi87 So you are using the same software in the same environnement like the reporter 6 years ago?

**Comment by KaKi87** [comment] 2025-02-14 16:18
As I said : **latest** Kiwix, **exact** same issue.
