### ISSUE TITLE
*.appimage doesn't start in Xubuntu 20.04

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#502] opened 2020-07-29 10:03 UTC
**Kiwix 2.0.4** (*.appimage) doesn't start in [**Xubuntu** 20.04](https://en.wikipedia.org/wiki/Xubuntu) (Xfce 4.14.2) (Kernel: 5.4.0-26 **64 bit**):
```
name@test:~/Documents$ ./kiwix-desktop_x86_64_2.0.4.appimage
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Library directory : "/home/name/.local/share/kiwix"
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Aborted (core dumped)
name@test:~/Documents$ [1:1:0100/000000.737263:ERROR:broker_posix.cc(41)] Invalid node channel message
Received signal 7 BUS_ADRERR 7f1bebe99560
name@test:~/Documents$ 
```
PS: in [**Xubuntu** 18.04.1](https://en.wikipedia.org/wiki/Xubuntu) - **Kiwix 2.0.4** is **successfully launched**!

**Comment by kelson42** [comment] 2020-07-30 08:59
Does this workaround allows to Kiwix Desktop to start normally?
```
MESA_LOADER_DRIVER_OVERRIDE=i965 ./kiwix-desktop_x86_64_2.0.4.appimage
```

If not, please share the command call with error log.

**Comment by Ubuntu-2020** [comment] 2020-07-31 09:07
@kelson42

**Xubuntu 20.04** (**Kernel**: 5.4.0-26-generic x86_64) **bits**: 64 (**Xfce** 4.14.2)
**Kiwix 2.0.4** (.appimage) **doesn't start**!

```
name@test:~/Documents$ MESA_LOADER_DRIVER_OVERRIDE=i965 ./kiwix-desktop_x86_64_2.0.4.appimage
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Library directory : "/home/name/.local/share/kiwix"
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Aborted (core dumped)
name@test:~/Documents$ [1:1:0100/000000.862844:ERROR:broker_posix.cc(41)] Invalid node channel message
Received signal 7 BUS_ADRERR 7f92cfce7560
name@test:~/Documents$ 
```

**Comment by kelson42** [comment] 2020-07-31 09:10
@Ubuntu-2020 You should test with http://tmp.kiwix.org/Kiwix-test_qt514-x86_64.AppImage

**Comment by Ubuntu-2020** [comment] 2020-07-31 16:56
@kelson42

**Kiwix-test_qt514-x86_64.AppImage** doesn't start in **Xubuntu 20.04**:
```
name@test:~/Documents$ ./Kiwix-test_qt514-x86_64.AppImage
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Library directory : "/home/name/.local/share/kiwix"
Compiled with Qt Version  5.14.2
Runtime Qt Version  5.14.2
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Aborted (core dumped)
name@test:~/Documents$ 
```

```
name@test:~/Documents$ MESA_LOADER_DRIVER_OVERRIDE=i965 ./Kiwix-test_qt514-x86_64.AppImage
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Library directory : "/home/name/.local/share/kiwix"
Compiled with Qt Version  5.14.2
Runtime Qt Version  5.14.2
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Aborted (core dumped)
name@test:~/Documents$ 
```

**Comment by kelson42** [comment] 2020-08-01 09:32
@Ubuntu-2020 Thank you for your feedback, I will close this ticket as duplicate of #486.

**Closed by kelson42** 2020-08-01 09:32 UTC
Labels: Linux, appimage, bug
