### ISSUE TITLE
*.appimage doesn't start in Ubuntu Studio 20.04

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#486] opened 2020-07-12 12:09 UTC
**Kiwix 2.0.3** (*.appimage) doesn't start in **[Ubuntu Studio](https://en.wikipedia.org/wiki/Ubuntu_Studio) 20.04** (Xfce).

**Comment by mgautierfr** [comment] 2020-07-13 12:28
Do you have the output/error message when you try to run it ?
Without it, it will be difficult to debug this.

**Comment by Ubuntu-2020** [comment] 2020-07-14 07:42
@mgautierfr More discussion [there](https://github.com/kiwix/kiwix-desktop/issues/480).

**Comment by kelson42** [comment] 2020-07-14 07:50
@Ubuntu-2020 Please don't comment on #480. To get the log, just open a terminal and type `kiwix-desktop` + ENTER. The log will appear on the the terminal.

**Comment by Ubuntu-2020** [comment] 2020-07-15 09:53
I entered different commands in the terminal but received the same response:
```
name@test:~$ kiwix-desktop
kiwix-desktop: command not found
name@test:~$ kiwix
kiwix: command not found
name@test:~$ kiwix-desktop_x86_64_2.0.3.appimage
kiwix-desktop_x86_64_2.0.3.appimage: command not found
```
But I should note that in **Ubuntu MATE 18.04** I also can't run (.appimage) via the terminal. But if I make a double-click on the file, then in **Ubuntu MATE 18.04** Kiwix **2.0.3** (.appimage) will start!
I also opened the terminal in the **Document**s folder (where ***.appimage** is located) and entered commands in the terminal. But the result was the same: `command not found`
Based on the above I come to the conclusion that I just enter the incorrect commands in the terminal.

**Comment by kelson42** [comment] 2020-07-15 09:55
@Ubuntu-2020 Sorry, I really have misguided you, it should be `$./kiwix-desktop_x86_64_2.0.3.appimage`. Before you should put the execution permission with `$chmod +x kiwix-desktop_x86_64_2.0.3.appimage`. Don't type the `$` sign, this is just to say this is the start of the prompt.

**Comment by Ubuntu-2020** [comment] 2020-07-15 13:58
***.appimage** is located in my **Documents** folder. Here are the messages from the terminal:

```
name@test:~/Documents$ ./kiwix-desktop_x86_64_2.0.3.appimage
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Library directory : "/home/name/.local/share/kiwix"
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Aborted (core dumped)
name@test:~/Documents$ [1:1:0100/000000.817342:ERROR:broker_posix.cc(41)] Invalid node channel message
Received signal 7 BUS_ADRERR 7fa6b72cf560
name@test:~/Documents$ 
```

**Comment by kelson42** [comment] 2020-07-15 14:08
Looks like a duplicate of #393, but there is nothing we can really do because this looks like to be a misconfiguration of the OPENGL system. @mgautierfr Anything to add?

**Comment by kelson42** [comment] 2020-07-16 08:13
@probonopd I believe your help would be welcome here, do you have any comment on this kind of problem?

**Comment by Spindletop** [comment] 2020-07-18 13:43
Similar issue on my system with Ubuntu 20.04 with KDE but slightly different error log:
```
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
```
The workaround as mentioned in #393 does work though:
`MESA_LOADER_DRIVER_OVERRIDE=i965 ./kiwix-desktop_x86_64_2.0.4.appimage`

**Comment by probonopd** [comment] 2020-07-23 19:26
What happens if you run the same AppImage on the same system on e.g., Ubuntu 18.04?

**Comment by kelson42** [comment] 2020-07-23 21:01
@probonopd I had not problem on 18.04 at the time I was using it.

**Comment by Spindletop** [comment] 2020-07-24 05:33
I suspect it has something to do with Intel graphic card drivers ("_Iris will replace the i915 driver as the default Intel GPU graphics driver for Broadwell (Gen (8) and newer iGPUs sometime in 2020_") and the issue should appear mostly on notebooks, because I assume mostly Nvidia or Amd graphic cards are present on Desktop systems.
The following seems now to be the default (but not on all systems) and will therefore lead to the mentioned error:
`MESA_LOADER_DRIVER_OVERRIDE=iris ./kiwix-desktop_x86_64_2.0.4.appimage`

**Comment by kelson42** [comment] 2020-07-28 12:30
@mgautierfr If this is problem is not fixeable in forseenable future. I would like to abandon the appimage format and come back to a normal tarball with binaries.

**Comment by probonopd** [comment] 2020-07-30 08:34
> @mgautierfr If this is problem is not fixeable in forseenable future. I would like to abandon the appimage format and come back to a normal tarball with binaries.

Since an AppImage is just a self-mounting disk image that executes whatever you have put inside, a normal tarball with binaries will have the exact same issues, as would have a zip file. This is not a question of the archive format.

**Comment by kelson42** [comment] 2020-07-30 08:36
@probonopd You confirm there is nothing specific related to Qt in the appimage packaging (process)?

**Comment by probonopd** [comment] 2020-07-30 08:40
Well. We need to distinguish two things:

* The AppImage format. You can put anything inside it. You decide. So you can put into an AppImage whatever you would put into a "normal tarball with binaries". Just add an AppRun file/link so that the AppImage knows what to execute. And some metadata like icons and a desktop file
* An AppImage that will run on all still-supported mainstream distributions. This is what we recommend. Which means that you will need to bundle Qt and those dependencies which cannot be expected to come with every still-supported mainstream distribution in a recent enough version. If you wanted to make a "normal tarball with binaries" that should run on all still-supported mainstream distributions without requiring the user to install anything, you would need to do the exact same things...

**Comment by kelson42** [comment] 2020-07-30 08:47
>     * An AppImage that will run on all still-supported mainstream distributions. This is what we recommend. Which means that you will need to compile on the oldest still-supported distribution, bundle Qt and those dependencies which cannot be expected to come with every still-supported mainstream distribution in a recent enough version. If you wanted to make a "normal tarball with binaries" that should run on all still-supported mainstream distributions without requiring the user to install anything, you would need to do the exact same things...

OK, but this has nothing to do with `appimage` in itself. Like you have written earlier, these are exactly the same constraints with a standard tarball! So like a standard tarball, appimage has really no Qt related special mgmt in its code base?

**Comment by probonopd** [comment] 2020-07-30 08:49
Correct.

**Comment by mgautierfr** [comment] 2020-07-30 08:54
>  Which means that you will need to compile on the oldest still-supported distribution

In that situation, we are compiling/packaging on a older distribution that the one we are launching the appimage. So it is a different "issue".

> "Iris will replace the i915 driver as the default Intel GPU graphics driver for Broadwell (Gen (8) and newer iGPUs sometime in 2020"

@Spindletop, do you have a source for that ?

If this is confirmed I'm afraid that all old Qt applications using opengl compiled on old system (if not all application using opengl, Qt or not) will stop to work because they cannot find the correct mesa driver.
In this case, it would be somehow a compatibility break on the distribution side :/

**Comment by Spindletop** [comment] 2020-07-31 06:11
@mgautierfr: please see https://linuxreviews.org/Intel_Iris, I'm sorry that I even quoted the wrong passage, it says `The Intel Iris driver is the default driver for Intel gen8-11 hardware in Mesa 20`. One can find out what is used by calling e.g.: 
```
$ glxinfo -B | grep Vendor
    Vendor: Intel (0x8086)
$ MESA_LOADER_DRIVER_OVERRIDE=iris glxinfo -B | grep Vendor
    Vendor: Intel (0x8086)
$ MESA_LOADER_DRIVER_OVERRIDE=i965 glxinfo -B | grep Vendor
    Vendor: Intel Open Source Technology Center (0x8086)
```
The short string is listed when Iris is used, the longer string is shown when the older i965 driver is used. For a list of Intel graphic cards see https://en.wikipedia.org/wiki/Intel_HD_and_Iris_Graphics, gen8 was starting in 2013.

**Comment by LaurentBonnaud** [comment] 2020-09-01 11:24
As suggested in other bug reports, running 

`MESA_LOADER_DRIVER_OVERRIDE=i965 ./kiwix-desktop_x86_64_2.0.4.appimage`

does work on my Ubuntu 20.04 system with an Intel GPU.

**Comment by probonopd** [comment] 2020-11-01 16:12
@stale

**Comment by kelson42** [comment] 2020-11-01 17:23
@mgautierfr I there anything we can do here? Sounds there like an ubuntu configuration problem!

**Closed** 2020-11-21 16:26 UTC
Labels: Linux, Qt, appimage, bug
