### ISSUE TITLE
kiwix server.exe can not run on Win server 2019

### ISSUE THREAD

**Issue by Jiangb2021** [kiwix/kiwix-desktop#715] opened 2021-11-02 01:44 UTC
kiwix server.exe can not run on Win server 2019

**Comment by Jiangb2021** [comment] 2021-11-02 01:45
Why del my issue?

**Comment by kelson42** [comment] 2021-11-02 06:29
Duplicate of https://github.com/kiwix/kiwix-tools/issues/494

**Closed** 2021-11-02 06:29 UTC
Labels: duplicate, question
