### ISSUE TITLE
Storage error

### ISSUE THREAD

**Issue by Bleda412** [kiwix/kiwix-desktop#857] opened 2022-07-03 00:34 UTC
I downloaded Kiwix and ran into an error about not having enough storage, despite having 6TB of space available on one drive alone. This occurred when I tried to download the text version of Wikipedia. If I tried to download a much smaller file, like Arch Wiki, the download starts right up. I sent a message via the contact form and was told to ask here. I am on Windows, and I have tried setting the download location to multiple different drives with enough space.

![kiwix storage error](https://user-images.githubusercontent.com/108597171/177020005-bfc18e46-9d6b-46ea-bfd3-6a95126e1b0f.png)

**Comment by veloman-yunkan** [comment] 2022-07-03 06:50
Duplicate of #854

**Closed by veloman-yunkan** 2022-07-03 06:50 UTC
