### ISSUE TITLE
Kiwix desktop not honoring OS dark vs light theme

### ISSUE THREAD

**Issue by deadlydud** [kiwix/kiwix-desktop#558] opened 2020-12-11 07:50 UTC
Hello. When opening kiwix desktop, and clicking on the file dialog, 
it opens dialog box that is near-unreadable when Kubuntu OS is set to dark theme.

Is there any export VAR=value that one can do before opening Kiwix to set kiwix into dark-theme mode?
perhaps something that QT would understand, ...
(I did not see such setting withing kiwix-desktop), I tried kiwix-desktop from both the
add-apt-repository ppa:kiwixteam/release  (apt install kiwix), as well as from
kiwix-desktop_x86_64_2.0.5.appimage (downloaded binary from https://www.kiwix.org/en/download/ )
the GNU/Linux – x86-64 bit binaries  version.

![image](https://user-images.githubusercontent.com/35307604/101877181-46916900-3b96-11eb-879e-4c57fb953700.png)

**Comment by kelson42** [comment] 2020-12-11 07:52
@deadlydud Thank you for your bug report, but I believe this is a duplicate of #320

**Closed by kelson42** 2020-12-11 07:52 UTC
