### ISSUE TITLE
Kiwix-serve not starting on K-Desktop 2.0.4 on Windows10

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#523] opened 2020-09-28 10:52 UTC
Tried on 2 different computers and got the same `an error has occured` message.

**Comment by kelson42** [comment] 2020-09-28 10:56
@mgautierfr We have again a problem with kiwix-serve on Windows. We will have now to fix this ticket, #477. @Popolechien Would you be able please to download the latest kiwix-tools for windows and let us know if kiwix-serve works "at all" for Windows?

**Comment by Popolechien** [comment] 2020-09-28 11:24
Downloaded kiwix-tools_win-i686-3.1.2-3.zip  and launched Kiwix-serve: did not get an error message, but did not get anything working either. I checked running tasks and nothing appeared. I did get a Windows security warning that prevented execution, but then when I went forward nothing really happened.

**Comment by kelson42** [comment] 2020-09-28 11:27
@Popolechien This confirms my guess that `kiwix-serve.exe` is not working at all!

**Comment by mgautierfr** [comment] 2020-09-28 12:41
@Popolechien How do you launch kiwix-serve ?

**Comment by Popolechien** [comment] 2020-09-28 12:42
@mgautierfr Double-click on it. Do you want me to try command line launch?

**Comment by mgautierfr** [comment] 2020-09-28 12:47
`kiwix-serve` without argument (what is done double-cliking on it) says you that you need to add argument, print help and exit. It is normal that nothing happen.

Can you run it from command line ?

- run `cmd`
- type `cd c:\path\to\directory\containing\kiwix-serve`
- type `kiwix-serve` (should print help message)
- type `kiwix-serve -p 8080 path\to\a\zim_file.zim` and then try to access `http://localhost:8080` from your web browser.

**Comment by Popolechien** [comment] 2020-09-28 12:58
w00t! That works.

**Comment by kelson42** [comment] 2020-09-28 13:00
@Popolechien OMG... we have not beeing good on that one.
@mgautierfr Good point! So luckily the problem seems only being the kind of interface with the binary. That does not change anything for the user... but this will be easier to fix.

**Comment by mgautierfr** [comment] 2020-09-28 13:07
Have you tried with the kiwix-serve you have downloaded (kiwix-tools_win-i686-3.1.2-3.zip) or the kiwix-serve packaged with kiwix-desktop (in same directory) ?

**Comment by Popolechien** [comment] 2020-09-28 13:15
Works in both cases.

**Comment by mgautierfr** [comment] 2020-09-28 13:34
I have no problem on my side using `kiwix-desktop_windows_x64_2.0.4-1` (and a virtual machine).
Just to be sure, have you zim file in the library (displayed in kiwix-desktop) ?

**Comment by kelson42** [comment] 2020-09-28 13:53
@Popolechien Would you be able to give a bit more details about what you are doing and getting please?

**Comment by Popolechien** [comment] 2020-09-28 14:02
Well unfortunately no: I launch `kiwix-desktop_windows_x64_2.0.4-1`, then go to `Local Kiwix Server` in the settings and click on Start Kiwix Server and get the standard error message. Nothing less, nothing more.

**Comment by mgautierfr** [comment] 2020-09-28 14:21
If I have no zim files on my local library I have indeed a error message when I try to launch a server.
This make sense as the local server as no files to serve and so exit early.
The check on kiwix-desktop side to verify that kiwix-serve is correctly run fails as kiwix-serve already stop.

@Popolechien is it your case ?

Whatever if this is the root cause of this issue, we should deactivate the local server is there is no zim to serve.

**Comment by Popolechien** [comment] 2020-09-28 14:26
I tried that too - having zim files in the same folder as Kiwix-serve, or downloaded from the application. Open or closed. It always gives me the same `An error has occured` message

**Comment by kelson42** [comment] 2020-09-29 13:54
It seems to work fine for me as well.

**Comment by kelson42** [comment] 2020-09-29 13:55
@mgautierfr But this is not normal:
* To not know more what goes wrong
* That kiwix-serve does not start properly without ZIM files

**Comment by kelson42** [comment] 2020-09-30 15:21
We should stop here to use `kiwix-serve.exe` and use directly the HTTP daemon provided by Kiwixlib.

**Comment by kelson42** [comment] 2020-10-16 12:39
@mgautierfr Can we close this ticket? Or do we depend on an unmerged PR?

**Comment by kelson42** [comment] 2020-10-16 13:51
Fixed via #528

**Closed by kelson42** 2020-10-16 13:51 UTC
Labels: bug
