### ISSUE TITLE
Search bar's accepted text length is too short

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#95] opened 2019-01-03 09:03 UTC
Again from OTRS:
"typing in the search bar of Wikipedia only allows you to type a maximum of 10 letters before it won't allow you to write anymore. It glitches and deletes what you have written and starts typing from the start. This makes it difficult when trying to search "Einsteins Second Law of Thermal Dynamics" and you can only type "Einsteins...""

**Comment by kelson42** [comment] 2019-01-09 18:57
@mgautierfr Tested with last beta and I confirm. Reaching a certain length the whole searbox is clear and the user has to start from the beginning.

**Comment by kelson42** [comment] 2019-05-17 10:44
Quite sure this is a duplicate of #149

**Closed by kelson42** 2019-05-17 10:44 UTC
Labels: bug, enhancement
