### ISSUE TITLE
Unable to open "Translations" in wiktionary:Offline

### ISSUE THREAD

**Issue by Fabrika2Grafem** [kiwix/kiwix-desktop#620] opened 2021-04-02 07:49 UTC
There's no [show] or [hide] on the bar.
Version of Kiwix : 2.0.4
Version of Wiktionary : wiktionary_en_all_maxi_2021-03.zim

Thank you!

**Comment by Fabrika2Grafem** [comment] 2021-04-02 07:55
- [bug]

**Comment by kelson42** [comment] 2021-04-02 07:58
Thx for the bug report, but this is a duplicate of https://github.com/openzim/mwoffliner/issues/1033

**Closed by kelson42** 2021-04-02 07:58 UTC
