### ISSUE TITLE
Should we keep the "open new (blank) tab button" ?

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#1063] opened 2024-03-20 16:00 UTC
Do we really need a button to open a new empty tab ? Should we remove it ? (I'm in favor of removing it)

_Originally posted by @mgautierfr in https://github.com/kiwix/kiwix-desktop/pull/1057#discussion_r1531899459_

**Comment by ShaopengLin** [comment] 2024-03-26 21:02
#140 will be a useful feature. Some feature additions on the new empty tab could make it very useful. Though before it is implemented, it does not really serve a purpose.

**Comment by kelson42** [comment] 2024-03-26 21:25
The button is just not finish to be implemented... there is already a ticket on that topic.

**Comment by ShaopengLin** [comment] 2024-03-26 21:49
Sorry I am not sure what is meant by "not finish to be implemented"? Could you point me to the ticket (did you mean #499 )?

Just to clarify I was justifying we should keep this button.

**Comment by kelson42** [comment] 2024-05-11 11:34
This is how it should look like
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/2201c06c-2fc1-4fef-bfef-ae07a12b18bc)

**Comment by kelson42** [comment] 2024-05-11 11:36
Duplicate of https://github.com/kiwix/kiwix-desktop/issues/140

**Closed by kelson42** 2024-05-11 11:36 UTC
Labels: question
