### ISSUE TITLE
Clicking on a search suggestion does not do anything

### ISSUE THREAD

**Issue by nickreserved** [kiwix/kiwix-desktop#207] opened 2019-07-20 19:47 UTC
Version: 2.0-beta5-18-gc42d2d0
OS: Windows 7 x64
ZIM: wikipedia_en_all_novid_2018-10.zim

Search is not working at all.
When I type something, like "Nuclear Fusion", suggested articles appear correctly but even when I press ENTER or I select suggested article from drop down list, nothing happens.
It is so rediculus that I believe it is my PC problem. But what problem can have my PC to disturb search of Kiwix?

I don't know how must work, but when I go to "Local Files", even when I just ...->File->Open File->Above_ZIM, it is empty.

**Comment by kelson42** [comment] 2019-07-20 19:53
@nickreserved If you use the mouse to click on the drop down list item you have chosen, does it works better?

**Comment by kelson42** [comment] 2019-07-21 10:58
I strongly suspect that this is a duplicate of #80. This should be fixed, would be nice to check again with a nighly https://download.kiwix.org/nightly/ or with the to be released soon RC1.

**Comment by nickreserved** [comment] 2019-07-25 06:32
Works fine on nightly Firefox plugin.

**Comment by kelson42** [comment] 2019-07-25 07:04
@nickreserved I'm still not sure to fully understand how to reproduce the problem as I miss a clear step-by-step procedure. You write for example "I select suggested article from drop down list", but I don't know if this is with the keyboard or with the mouse. You say also "nothing happens", but does that mean for example that the list of suggestions does not disappear? As a matter of fact, I can not reproduce the problem for now.

**Comment by metal450** [comment] 2019-07-26 01:41
I also can't get search to work at all.  Like the OP says: I type & see results, but hitting enter (and also clicking on the items) does nothing.  Basically search is unusable.

**Comment by kelson42** [comment] 2019-07-26 06:33
@metal450 Are you sure your are using the beta5? What happen exactly after clicking on <enter> (do you get a blanck page,You keep the already loaded page or a blank page? Does the random article feature works fine?

**Comment by metal450** [comment] 2019-07-26 07:21
Beta4.  That's the version currently linked from https://www.kiwix.org/en/downloads/.

**Comment by kelson42** [comment] 2019-07-26 07:26
@metal450 There is no download link to Kiwix-Desktop in https://www.kiwix.org/en/downloads/. The link is in https://www.kiwix.org/en/downloads/kiwix-reader/... and it points properly to the beta5. Please test again with beta5 and let us know.

**Comment by metal450** [comment] 2019-07-26 07:35
>>There is no download link to Kiwix-Desktop in https://www.kiwix.org/en/downloads/

This sure looks like a link to Kiwix-Desktop to me (see video, it's beta4): https://lnk2.tk/snaps/2019-07-26_00.31.52.mp4

Yes, downloading beta5 from that other link seems to fix it.

**Comment by kelson42** [comment] 2019-07-26 07:39
@metal450 Thank you for your feedback. Looks like I'm blind! The links are wrong and will be fixed https://github.com/kiwix/web/issues/76. Really happy to see that the problem is fixed for you.

**Comment by kelson42** [comment] 2019-07-26 07:41
@nickreserved Would you be able to provide a video of the problem please? We are not able to reproduce it.

**Comment by lpqi** [comment] 2019-07-28 03:53
beta5:
search is not work;
local file list is empty

beta3 search is work well,but local file list is empty even I had open a zim file.

Kiwix 0.9 is my favorite version,but it can not open "wikipedia_en_all_novid_2018-10.zim"

**Comment by kelson42** [comment] 2019-07-28 04:58
@lpqi If you have no file in your library then this is normal than you have no search. Download oe load a ZIM file first. This has anyway no relation to the original bug report. Please open a new ticket if you have an other problem.

**Comment by kelson42** [comment] 2019-08-05 13:48
@nickreserved We have released the 2.0-rc1 which bring many improvments around suggestions. Would you be please able to give it a try and let us know if you still have problems?

**Comment by nickreserved** [comment] 2019-08-06 08:59
Seems working with english ZIMs. I will try non-english.

**Comment by nickreserved** [comment] 2019-08-15 20:49
No.
My previous post is wrong.
Nothing is working.
I open ZIM but KIWIX does not keep them. Every time I must File-Open them.
I open english wikipedia ZIM and it works for 1-3 articles. Not more.
I open GREEK wikipedia ZIM and nothing works. Probably you are screwed with charsets.

Guys, sorry but I will become rude: This app needs at least 100 years of development before next release.

**Comment by kelson42** [comment] 2019-08-15 21:29
@nickreserved So your are still unable to open the article "Nuclear fusion" from the search box? This is the topic here.

**Comment by nickreserved** [comment] 2019-08-16 15:02
Yes! First time works.
After 2-6 articles does not work.

Sorry, but I don't want to participate on this project via bug reporting anymore.
I believe kiwix-desktop is totally crippled and I already removed any version of Kiwix-Desktop from my PC (RC or stable(!) ).
I found my solution in Firefox addon. Great project.

**Comment by kelson42** [comment] 2019-08-16 18:51
Works for me, can not reproduce.

**Closed by kelson42** 2019-08-16 18:51 UTC
Labels: bug, duplicate, question
