### ISSUE TITLE
Kiwix windows application will not start

### ISSUE THREAD

**Issue by Drakior** [kiwix/kiwix-desktop#879] opened 2022-09-04 17:28 UTC
I extract the program onto desktop, I click on application. Nothing happens.

Antivirus is not stopping it.

I don't know what is going in with it.

**Comment by kelson42** [comment] 2022-09-04 17:40
What have you downloaded exactly? Which URL?

**Comment by Drakior** [comment] 2022-09-04 22:00
I downloaded https://www.kiwix.org/en/downloads/windows/ the 64bit version

**Comment by Drakior** [comment] 2022-09-05 00:59
> What have you downloaded exactly? Which URL?

I downloaded https://www.kiwix.org/en/downloads/windows/ the 64bit version

**Comment by Drakior** [comment] 2022-09-07 21:34
No one have an idea s to the cause to this issue?

**Comment by kelson42** [comment] 2022-09-08 05:56
@Drakior This is the usual behaviour when people don't extract and launch kiwix directly from the ZIP file. Maybe you can make a screencast of what you do? You can also try to start the kiwix-desktop.exe from the commandline to see the error printed there.

**Comment by Painless68** [comment] 2022-11-02 18:22
kiwix-desktop.exe doesn't do anything for me, I'm on Windows 11. I was using 2.2.2 and just updated to 2.3.0 and it is the same problem, nightly version opens "kiwi" in terminal but just closes after a couple seconds. I tried the old version I have downloaded, 2.0.4-1, and it works fine.

**Comment by kelson42** [comment] 2023-08-12 08:43
I suspect the ZIM is not unpacked or something similar, without more details (a screencast, a lof of the terminal, ...) I will have to close the ticket. because we have too few information.

**Comment by dardoor** [comment] 2023-09-15 19:16
I occasionally experience this problem too. I double-click kiwix-desktop.exe, but the app doesn't open. But the Kiwix process is still visible in Task Manager and it's using some CPU (I have to kill it there). It's similar to [this bug](https://github.com/kiwix/kiwix-desktop/issues/987), except that I don't have an entry in Event Viewer.

This only happens occasionally, most of the time Kiwix opens normally, so it's hard to reproduce or find an obvious cause.
But I'll say this, for what it's worth: I think it can make a difference from where the executable is launched. I once noticed that it opened fine if launched from Total Commander, but when I tried to launch it from Windows Explorer it failed repeatedly, several times. This was only happening on that day, not always. I've also seen it fail when launched from Total Commander.

(and I downloaded it from https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64.zip)

**Comment by kelson42** [comment] 2024-04-12 08:13
Maybe a duplicate of #893

**Comment by kelson42** [comment] 2024-05-12 08:32
@Drakior @Painless68 @dardoor Thank you for keeping this ticket alive. That said, we have almost no details about your cases and this makes the analysis very complicated as there is not clear reproduction case on our side. It is very probable that you don‘t all suffer of the them bug. We are tackling the last issues of next release `2.4.0` and this issue is one of them. This new release is really focused on removing crash scenarios and we already have fixed a few of them. To try to move forward, would you please:
* try with latest nighly http://download.kiwix.org/nightly/
* If this still crash at start, try to launch from the command line and share the output with us

**Comment by Painless68** [comment] 2024-05-12 15:21
I think this is just the same issue from #893 , I assume it's a problem with the Roaming folder such as library.xml when upgrading from 2.0.1 or 2.0.4-1 to 2.3.0 because since I did a fresh reinstall of Windows 11 last year I've been using 2.3.1 fine.

**Closed** 2024-05-12 15:51 UTC
Labels: question

**Comment by EnkiSun86** [comment] 2024-08-01 02:27
I encounter the same problem. I fixed this by deleting the Kiwix folder from Roaming. However, I did not check the error log, and I am not sure if this problem same as #893.
