### ISSUE TITLE
Menu bad positions on Wayland

### ISSUE THREAD

**Issue by ynikitenko** [kiwix/kiwix-desktop#432] opened 2020-04-27 08:56 UTC
I'm using Kiwix-desktop 2.0.1 installed from flathub on Fedora Core 29, with Gnome and Wayland. Steps to reproduce:

    open kiwix-desktop, open a Zim file
    call a menu and a submenu

The menu appears at different places. The submenu (View) too, often its items are invisible. Sometimes the submenu doesn't appear at all. I attach screenshots.

How it should be:
The menu should be opened always at one place (if the current size of the application is unchanged). The submenus should be opened next to the menu. They should be always visible.

![Screenshot from 2020-04-27 11-25-29](https://user-images.githubusercontent.com/1204978/80353137-94fb2d00-887d-11ea-94ba-8bbf1ff92909.png)
![Screenshot from 2020-04-27 11-27-04](https://user-images.githubusercontent.com/1204978/80353141-97f61d80-887d-11ea-803e-076c26886c00.png)

**Comment by mgautierfr** [comment] 2020-04-27 12:07
I'm not sure there is a lot to do here, except moving to more recent version of Qt (https://github.com/kiwix/kiwix-build/issues/403) and hopping that the issue is solved.

The placement of the submenu is base on the interaction between Qt and the wayland compositor (gnome-shell here). We do not control this.

Somehow related to #365

**Comment by kelson42** [comment] 2020-04-27 12:43
OK, lets move to new version of Qt and see if we still have the problem with Wayland. If this is still the case, we should probably open a ticket upstream (or find one).

**Comment by kelson42** [comment] 2021-06-30 20:09
@ynikitenko Is that bug fixed with latest nightly https://download.kiwix.org/nightly/2021-06-30/kiwix-desktop_x86_64_2021-06-30.appimage which now use recent version of Qt (5.15)?

**Comment by ynikitenko** [comment] 2021-07-01 14:14
@kelson42 currently I'm using Arch Linux, Kiwix Version = 2.0.5. This bug is not present here, so I probably won't be able to see the difference. However, I'll try Fedora Core on another laptop in several weeks (or months, can't know it for sure, sorry! Feel free to ping me in the end of July).

**Comment by ynikitenko** [comment] 2021-07-01 16:08
I can't run this appimage on Arch Linux,

> ./kiwix-desktop_x86_64_2021-06-30.appimage: symbol lookup error: ./kiwix-desktop_x86_64_2021-06-30.appimage: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm, version Qt_5

I'm afraid I won't be able to run that on Fedora as well, because on my old laptop Fedora is pretty old too (and Qt was probably not updated there since a long time, as is usual with fixed release distros).

**Comment by kelson42** [comment] 2021-07-15 05:05
Yes, we need Qt5 to fix this problem. closing for the moment, if this reappear, then please reopen the ticket.

**Closed by kelson42** 2021-07-15 05:05 UTC
Labels: Qt, bug, question
