### ISSUE TITLE
Add logo to Kiwix desktop.exe

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#224] opened 2019-08-08 12:08 UTC
It's not much but considering the long list of files available in the folder, it would certainly help users identify which executable to run.
This logo would perfectly do: https://commons.wikimedia.org/wiki/File:Kiwix_icon_transparent.svg

![Sans titre](https://user-images.githubusercontent.com/21675885/62701991-f294d400-b9e5-11e9-8411-d5e49d58b4bf.png)

**Comment by kelson42** [comment] 2019-08-08 12:12
Duplicate of #187

**Closed by kelson42** 2019-08-08 12:12 UTC
Labels: duplicate, enhancement
