### ISSUE TITLE
Library error: Language option weird

### ISSUE THREAD

**Issue by Rexadev** [kiwix/kiwix-desktop#943] opened 2023-05-15 19:11 UTC
![image](https://github.com/kiwix/kiwix-desktop/assets/62152714/1f3bea9e-2017-46fa-a5fb-9e85c74ebd72)

**Comment by kelson42** [comment] 2023-08-03 16:42
@Rexadev Do you use kiwix-serve or the server version of kiwix-desktop? I believe this is a duplicate of https://github.com/kiwix/libkiwix/issues/908 and therefore fixed and released for kiwix-serve and in [nightlies](https://download.kiwix.org/nightly/) for kiwix-desktop. Can you please confirm?

**Comment by Rexadev** [comment] 2023-08-03 17:14
@kelson42 screenshot is og the library website

**Closed** 2023-08-03 18:01 UTC
Labels: bug
