### ISSUE TITLE
Create an Installer for Windows (msi or exe)

### ISSUE THREAD

**Issue by amirrammari** [kiwix/kiwix-desktop#323] opened 2019-12-02 18:12 UTC
Hello, Kiwix desktop is a portable app.
Please create an installer for Windows (MSI or EXE)
Thanks.

**Comment by kelson42** [comment] 2019-12-02 18:14
@amirrammari Is that not a duplicate of  #314 ?

**Comment by amirrammari** [comment] 2019-12-02 18:18
#314 is the package for Windows 10 (`.AppX` `.AppxBundle` `.Msix` `.MsixBundle` `.MsixUpload` `.AppxUpload` `.XAP`)
I need an installer for windows 7 (.MSI or .EXE)

**Comment by kelson42** [comment] 2019-12-02 18:19
As far as I know the installation process on Windows7 is not different from Windows10

**Closed by kelson42** 2019-12-02 18:19 UTC
Labels: enhancement, question

**Comment by amirrammari** [comment] 2019-12-02 18:21
Ok, I will close this issue.

**Comment by amirrammari** [comment] 2019-12-02 18:22
Ok, you can close this issue.
