### ISSUE TITLE
Beta does not play TED videos

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#94] opened 2019-01-03 08:58 UTC
From OTRS:
"I've only had one glitch since using the "Windows 10 (v2 beta)" regarding the Ted Talks (all of them), specifically video not playing (there is audio though).

Laptop
Acer Predator G9 17.3"
Intel® Core™ i7-6700HQ Processor (6M Cache, up to 3.50 GHz )
Nvidia GTX1070
16GB RAM
256GB SSD + 1TB
Windows 10 Home
Latest Windows updates installed, latest graphics card driver updates installed."

**Comment by kelson42** [comment] 2019-01-27 07:39
Duplicate of https://github.com/kiwix/kiwix-desktop/issues/39

**Closed by kelson42** 2019-01-27 07:39 UTC
Labels: bug
