### ISSUE TITLE
Windows-only autoscroll feature is broken in full screen

### ISSUE THREAD

**Issue by gmikhail** [kiwix/kiwix-desktop#913] opened 2022-12-26 20:31 UTC
1. Open page with long content.
2. Enter full screen mode (F11).
3. Press the middle mouse button in an empty area of the page (where there are no links, just text or blank space) and drag the mouse up or down. The mouse cursor changes, but the scroll does not work. 

<s>PS: also noticed that I can't even drag the scrollbar with the mouse in full screen mode.</s> see https://github.com/kiwix/kiwix-desktop/issues/985

Version: 2.3.1
Windows 10 Pro 22H2 (build 19045.2364)

**Comment by kelson42** [comment] 2023-08-11 19:11
> PS: also noticed that I can't even drag the scrollbar with the mouse in full screen mode.

Confirmed, I have open a dedicated ticket at #985

**Comment by kelson42** [comment] 2023-08-11 19:17
@gmikhail I feel slightly stupid, but I'm not familliar with that "gesture". For me on Linux, nothing happens at all, not even the pointer is changing! But if I do the same on Chrome or Firefox, nothing happens either! I'm puzzled.

After researching a bit it seems you talk about a feature called autoscroll which is indeed Windows specific (if I understand properly)... but FF/Chrome users have extensions https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan.

@gmikhail Do I get it right?

**Comment by gmikhail** [comment] 2023-08-12 06:24
@kelson42 Yes, it's a Windows-specific feature. On Windows systems, on web pages (not only in browsers, but also in web-based desktop apps like Spotify or Steam) clicking the middle mouse button enables page scrolling. After that a scroll icon appears, and you can simply move the mouse and the page will scroll in that direction.

![](https://github.com/kiwix/kiwix-desktop/assets/4838367/544d009b-e4dc-4f75-ad43-bef00e5b33e2)

I don't use Linux, so my knowledge may be quite general. In short, in Linux, for historical reasons, the middle mouse button is used to insert text.

Note: in fact, in Firefox on Linux, you can enable a similar behavior (Settings -> General -> Browsing -> Use autoscrolling), but this is a feature at the app level, not the system, as in Windows.

---

The main problem is that in the Kiwix app, scrolling with the middle mouse button does not work **only** in full screen mode. In normal mode, everything works.

![](https://github.com/kiwix/kiwix-desktop/assets/4838367/13ab893f-6f03-4a34-91c6-1beaf54e0e52)

**Comment by kelson42** [comment] 2023-08-12 06:32
@gmikhail Thank you very much for the clarification. We shuld indeed try to fix that bug.

**Comment by sgourdas** [comment] 2024-03-20 21:57
@kelson42 my commit for #984 I think should have fixed the problem for this issue as well. Sadly, I am using WSL and am unable to test it since the middle click event will not go through.

Please let me know if there is something we can do from now, or maybe wait for the PR of #984 to be merged and check on the Windows version.

**Closed** 2024-04-12 07:23 UTC
Labels: bug, Windows
