### ISSUE TITLE
Search bar doens't search after copy/cut text from other programs

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#301] opened 2019-11-18 08:14 UTC
#287 is not responding, so I repost the edited essay here.
(1) Open some other program, notepad.exe suggested.
(2) Open wikipedia_en_all_nopic_2019-10.zim using kiwix-desktop_windows_x64_2.0-rc3, input(or paste) a keyword like "Dog" then press enter to show the page
Better to run kiwix after the above program. Sometimes the bug won's show up if you run kiwix before that.
(2) Switch to the above program, copy/cut something like "Dog", then paste it to kiwix and Enter, then kiwix's search bar won't show page any more. If not work, copy/paste again.

**Comment by kelson42** [comment] 2019-11-18 16:25
@wgt98 Opening twice the same ticket does not help. Please don't do that. 
Duplicate of #287

**Closed by kelson42** 2019-11-18 16:25 UTC
