### ISSUE TITLE
Some zim files are unavailable

### ISSUE THREAD

**Issue by voillyied8122** [kiwix/kiwix-desktop#824] opened 2022-03-28 11:50 UTC
Application: kiwix-desktop_windows_x64_2.0.5 & kiwix-tool_linux-armhf-3.2.0

Files:
lowtechmagazine.com_en_all_2021-12.zim
fas-military-medicine_2022-03.zim
ready-gov_2022-03.zim
cheatography.com_en_all_2022-03.zim

The zim files seems unavailable when use kiwix reader on Windows. It seems the kiwix server will be available so I tried it later.
![win](https://user-images.githubusercontent.com/56959893/160391794-b4eeb19b-f12d-4d90-a446-b86faa5c093c.JPG)

This time I use kiwix hotspot and visit them with another device, but it was still unavailable.
![server](https://user-images.githubusercontent.com/56959893/160391887-5ae67cdd-8765-4671-bff6-fd86c3031dc7.jpg)

**Comment by kelson42** [comment] 2022-03-28 12:05
This is a duplicate of https://github.com/kiwix/kiwix-desktop/issues/487. These files can still not be directly readble in Kiwix-Deskotp. But you can start the kiwix-serve mode and the read them from localhost `http://127.0.0.1` in your browser.

**Closed by kelson42** 2022-03-28 12:05 UTC
Labels: bug, question

**Comment by voillyied8122** [comment] 2022-03-28 12:21
> This is a duplicate of https://github.com/kiwix/kiwix-desktop/issues/487. These files can still not be directly readble in Kiwix-Deskotp. But you can start the kiwix-serve mode and the read them from localhost `http://127.0.0.1` in your browser.

How about read them from a raspberry pi-based kiwix server (not the server mode of kiwix reader on Windows)? It seems unable to just change the IP to visit these pages

**Comment by mgautierfr** [comment] 2022-03-28 12:32
> How about read them from a raspberry pi-based kiwix server (not the server mode of kiwix reader on Windows)? It seems unable to just change the IP to visit these pages

You must set a https service (kiwix-serve + ssl certificate). This is a requirement from ServiceWorker.

**Comment by kelson42** [comment] 2022-04-05 17:08
@voillyied8122 First we need to understand. Please open a ticket on kiwix-tools and explain what you do exactly, what you get and what you expect.
