### ISSUE TITLE
Upload of 2.4.0 PPA fails

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1285] opened 2024-12-15 09:19 UTC
... although it works fine with dev!

https://github.com/kiwix/kiwix-desktop/actions/runs/12331074751

**Comment by veloman-yunkan** [comment] 2024-12-16 09:39
The problem seems to be related to `libkiwix`:

>     Broken kiwix-build-deps:amd64 Depends on libkiwix-dev:amd64 < none -> 14.0.0~focal @un uN > (>= 14.0.0)
>      Removing kiwix-build-deps:amd64 because I can't find libkiwix-dev:amd64

Same situation in all three build jobs ([focal](https://github.com/kiwix/kiwix-desktop/actions/runs/12331074751/job/34417254341), [jammy](https://github.com/kiwix/kiwix-desktop/actions/runs/12331074751/job/34417254192), [noble](https://github.com/kiwix/kiwix-desktop/actions/runs/12331074751/job/34417254047)).

**Comment by kelson42** [comment] 2024-12-16 11:25
So far I agree :)

**Comment by veloman-yunkan** [comment] 2024-12-17 14:10
The problem comes from the version requirements of the `libkiwix-dev` dependency in `debian/control` - `libkiwix-dev (>= 14.0.0)` doesn't work, whereas `libkiwix-dev (>= 13.0.0)` works and results in resolving the dependency to `libkiwix-dev amd64 14.0.0~focal`. Will investigate further why it behaves in such a strange way.

**Comment by veloman-yunkan** [comment] 2024-12-17 14:45
> The problem comes from the version requirements of the `libkiwix-dev` dependency in `debian/control` - `libkiwix-dev (>= 14.0.0)` doesn't work, whereas `libkiwix-dev (>= 13.0.0)` works and results in resolving the dependency to `libkiwix-dev amd64 14.0.0~focal`. Will investigate further why it behaves in such a strange way.

`libkiwix-dev (>= 14.0)` works. I don't know what's wrong with `libkiwix-dev (>= 14.0.0)`. 

Submitted PR #1288 with that small change.

**Comment by veloman-yunkan** [comment] 2024-12-17 15:36
@kelson42 I don't know. @legoktm May provide a more substantiated answer.

**Comment by veloman-yunkan** [comment] 2024-12-17 15:40
But if we do, we probably should shorten the version strings in the `libzim` requirements too.

**Comment by kelson42** [comment] 2024-12-18 05:11
@veloman-yunkan Not to libzim... but if confirmed to work, this fix will have to be applied to libkiwix, zim-tools and kiwix-tools.

That said, how do you explain that the dev PPA is not impacted?

**Comment by veloman-yunkan** [comment] 2024-12-18 06:44
> Not to libzim...

@kelson42 I think you misunderstood. I meant the libzim dependency of kiwix-desktop debian conrol file.

**Comment by veloman-yunkan** [comment] 2024-12-18 06:46
> That said, how do you explain that the dev PPA is not impacted?

I have no explanation for that fact. Should I investigate further to find the root cause?

**Comment by kelson42** [comment] 2024-12-18 06:51
@veloman-yunkan Yes please, we deeply suffer since years of our lack of understanding around PPa. I would love to have more understanding and stability and control around this.

**Closed** 2024-12-18 08:28 UTC
Labels: Linux
