### ISSUE TITLE
local kiwix repositories

### ISSUE THREAD

**Issue by Boruch-Baum** [kiwix/kiwix-desktop#319] opened 2019-12-02 16:43 UTC
Using the linux appimage for kiwix 2.0-rc4, there is no clear way to set a default directory for storing downloaded zim files or for setting a default storage or reference directory. Also, there is no way to bulk add prior downloads to the collection displayed in the current appimage version

**Comment by kelson42** [comment] 2019-12-02 16:46
@Boruch-Baum Seems to be a duplicate of #170 ?!

**Comment by Boruch-Baum** [comment] 2019-12-02 17:06
I can agree to that, but this report is just a subset of what @gmikhail reported in #170, and is for a different version (linux instead of windows, rc4 instead of beta-xx). If it makes your work easier, you can close this as a kind-of duplicate.

However, I do want to point out that this issue is sort of more than just an enhancement. Any user of a prior version of kiwix is likely to have spent a lot of bandwidth (possibly with a lot of time and frustration) downloading zim files, and this issue makes it appear that the user has 'lost' her prior downloads with the upgrade! Of course, if the user is persistent, she'll eventually figure out that that she can use the menu option file > open to access her prior downloads, but not all kiwix users are going to notice that.

A very simple temporary solution would be to present a "welcome" documentation paragraph when opening a new kiwix install.

**Comment by kelson42** [comment] 2019-12-02 17:09
@Boruch-Baum I understand what you mean, this is a bit unfortunate. But Kiwix Desktop 1.0 is displaying where the files (the profile) are and then these files can be loaded manually in Kiwix Desktop 2.0.

**Closed by kelson42** 2019-12-02 17:09 UTC
Labels: enhancement, question
