### ISSUE TITLE
Suggestion system goes unstable over time

### ISSUE THREAD

**Issue by ynikitenko** [kiwix/kiwix-desktop#1019] opened 2023-12-04 15:19 UTC
I use Wiktionary as a dictionary. I translate many words one by one, but at some point the search bar just stops working. I have to close the tab and open the ZIM file anew.

Steps to reproduce:

1. Open Kiwix and load a local file.
2. Type a word in the search bar, get the search result (open the respective page).
3. Repeat this several times. After 3-5 words search stops working: the suggestions appear, but they are inactive (one can't type Enter or press the line with the mouse, because nothing changes).

Version: 2.3.1, Arch Linux, X11.

**Comment by ynikitenko** [comment] 2023-12-04 15:21
I wrote about that in #395; some things have improved since then. I can use the newest Kiwix version now! But it's still not perfect.

**Comment by kelson42** [comment] 2023-12-10 16:50
@ynikitenko Thank you for your bug report, I will try to reproduce.

**Comment by kelson42** [comment] 2024-04-29 19:43
@ynikitenko We are about to release soon version `2.4.0` and have tried to reproduce your bug but I can't. Not sure if it has been fixed or if I fail to recreate the condition you have on your computer. I would recommend to test with the latest nightly and let us know if you still have this problem https://download.kiwix.org/nightly/2024-04-29/kiwix-desktop_x86_64_2024-04-29.appimage. If this is the case pleas e share the exact ZIM files and the exact search terms you are using.

**Comment by ynikitenko** [comment] 2024-04-30 08:40
My version is 2.3.1. The bug is still there, unfortunately.
Probably I should better try after you release the new version?

**Comment by kelson42** [comment] 2024-04-30 08:43
@ynikitenko Version of the nightly build has not been updated, but this is a new piece of new code. Please share the detail of your scenario via text or you can also make a screencast if this is easier.

**Comment by kelson42** [comment] 2024-05-11 11:37
@veloman-yunkan Might that be that is somehow related to a very slow storage backend?

**Comment by ynikitenko** [comment] 2024-05-11 17:02
Sadly I could not run the new *appimage*. On Arch Linux it gave me an error similar to #225 :

`./kiwix-desktop_x86_64_2024-04-29.appimage 
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
/tmp/.mount_kiwix-ZdAhf6/usr/libexec/QtWebEngineProcess: symbol lookup error: /tmp/.mount_kiwix-ZdAhf6/usr/libexec/QtWebEngineProcess: undefined symbol: _ZN11QtWebEngine11processMainEiPPKc, version Qt_5
/tmp/.mount_kiwix-ZdAhf6/usr/libexec/QtWebEngineProcess: symbol lookup error: /tmp/.mount_kiwix-ZdAhf6/usr/libexec/QtWebEngineProcess: undefined symbol: _ZN11QtWebEngine11processMainEiPPKc, version Qt_5
[5890:5890:0511/183106.526645:ERROR:extension_system_qt.cpp(121)] Failed to parse extension manifest.
Segmentation fault (core dumped)
`

I tried to build it from source using [AUR](https://aur.archlinux.org/packages/kiwix-desktop-git), but it also produced an error.
I would wait for the package to be updated in the official repository, and then send you the results.

**Comment by ynikitenko** [comment] 2024-05-11 17:05
> @veloman-yunkan Might that be that is somehow related to a very slow storage backend?

I have an SSD drive. Everything works very quickly (as well as Kiwix, when it gives me results).

**Comment by kelson42** [comment] 2024-05-19 10:50
@ynikitenko Flatpak version has the same version release, so `2.3.1`, but you can test the latest Flatpack nightly https://download.kiwix.org/nightly/org.kiwix.desktop.flatpak.
@ynikitenko Very sorry to see that you are not able to run the appimage, could you please open a dedicated issue for that? This seems really not normal.
@veloman-yunkan I'm not able to reproduce this problem at all. Assigning to you to see if you have more success.

**Comment by kelson42** [comment] 2024-12-24 09:06
@ynikitenko We just have released the version `2.4.1` of Kiwix. This new version brings a lot of fixes around the search bar. I would like to refresh this issue with your help and see if this is still and issue (or not). Would you be able please to run `2.4.1` and let us know if you have still the same bugy behaviour? Another one... or maybe the bug is fixed?

**Comment by ynikitenko** [comment] 2024-12-25 13:24
This is great news and thanks for your work!
I've flagged the Arch Linux package outdated. Shall wait until they update that and then write back to you.

**Comment by kelson42** [comment] 2024-12-25 14:30
@ynikitenko OK, this might take a while. You can test with the appimage or with the flatpak version? Otherwise I would close the issue... but you could still leave your feedback later.

**Comment by ynikitenko** [comment] 2024-12-25 18:46
Hi Kelson,
I believe it will take much less time than your release.
Maybe you appreciate my notification of the maintainer and give them some
time?

Kelson ***@***.***> schrieb am Mi., 25. Dez. 2024, 15:30:

**Comment by kelson42** [comment] 2024-12-25 18:58
@ynikitenko @hasworks knows already and follows our release accurately anyway, see https://github.com/kiwix/kiwix-tools/issues/696#issuecomment-2543370849. He faces anyway difficulties letting me things that it could take weeks if not monthes to get this integrated in archlinux.

I'm sure you can understand that we can not make our ticket lifecycle depending on a third party distribution. I'm glad to reopen the issue if the bug is not fixed or not fixed properly.

**Closed by kelson42** 2024-12-25 18:58 UTC
Labels: bug, question, search

**Comment by ynikitenko** [comment] 2024-12-30 23:26
Hi @kelson42 , I've just checked the flatpak version.
That worked like charm! The search is stable over time (I don't have to reopen zim files). I can use keyboard shortcuts to navigate to the search bar. Translations are shown. I could even open several different wiktionaries in two tabs!
Because of the previous problems I could use only the wiktionary from 2016 and the corresponding ancient kiwix binary. It was a deal-breaker (however, I also have kiwix on my smartphone and tablets, so it was not that bad; and I could use online wiktionary also quite often). Now it's much better. Looking forward to getting a native Arch version of Kiwix!
Thanks a lot for your (and of all maintainers') work! Hope my numerous issues have been useful :)
I wish you Happy New Year!
Hopefully stay in touch.
Best, Yaroslav

**Comment by kelson42** [comment] 2024-12-31 06:55
@ynikitenko Glad to read so kany things work better! We always appreciate good written issues, they are essential to imporve the software. Feel free to open new ones!
