### ISSUE TITLE
Unable to open link

### ISSUE THREAD

**Issue by HanYoung-uwu** [kiwix/kiwix-desktop#590] opened 2021-02-05 07:23 UTC
Steps to reproduce:

    Load Wikipedia ZIM file.
    Open the ZIM file.
    Click on a link
Expected Result:
    Kiwix open the link

Observed Result:
   
![Kiwix_Desk_Screenshot_20210205_151840](https://user-images.githubusercontent.com/76819220/107002299-fd404d00-67c5-11eb-8752-5a8bf7ec3be1.png)

System configuration:

    Kiwix version: git master
    OS: Arch Linux

**Comment by HanYoung-uwu** [comment] 2021-02-05 08:21
After [this](https://github.com/kiwix/kiwix-desktop/commit/f240ea78a144cf0aa15d10edbeda42d8fef77b22) commit I'm unable to open link.

**Comment by kelson42** [comment] 2021-02-05 10:15
@HanYoung-uwu Works for me, do you use latest git master libzim/libkiwix?

**Comment by HanYoung-uwu** [comment] 2021-02-05 10:23
> @HanYoung-uwu Works for me, do you use latest git master libzim/libkiwix? Which ZIM file exactly? Which page and which link exactly?

I'm on ArchLinux so I guess lastest release. All links are affected. Was there some changes would cause this in libzim/libkiwix? I've found a workaround.

**Comment by kelson42** [comment] 2021-02-05 10:31
uninstall arch versions, and compile libzim/libkiwix by yourself. We have a massive change a libzim level currently ongoing.

**Comment by kelson42** [comment] 2021-02-05 10:31
Closing for the moment as I get this is the root cause.

**Closed by kelson42** 2021-02-05 10:31 UTC
Labels: question

**Comment by HanYoung-uwu** [comment] 2021-02-05 11:23
Comfimed it's caused by outdate libzim/libkiwix
