### ISSUE TITLE
UX for first-time users: Tell the user explicitly where to get files

### ISSUE THREAD

**Issue by suterma** [kiwix/kiwix-desktop#663] opened 2021-07-20 07:34 UTC
Upon starting kiwix-desktop (on Ubuntu 20.04) the user is presented with this screen:
![Screenshot from 2021-07-20 09-27-03](https://user-images.githubusercontent.com/11473920/126279704-78a0d856-63c7-4757-a7a9-cb2f891ed90f.png)

IMHO it's not clear where to get content. It personally took me a while to figure it out.

I would have expected to see a "Download Content" Button or menu entry. Maybe an "Archive" or Library tab. The "Plus" sign did also not help.....

I suggest either
 
1. start the UI on the "All Files" pane at first statup
2. Add a new specific pane with something like "Get Content", "Download Content" or similar and start there, at least on first  startup

Notes:

- To still maintain the "auto-load"-Feature for existing local content (https://github.com/kiwix/kiwix-desktop/issues/644), the point 1) above could be conditionally only be done if there is no local content yet available
- This is somewhat a reiteration of https://github.com/kiwix/kiwix-desktop/issues/555, with a new proposal

**Comment by kelson42** [comment] 2021-07-20 12:06
@suterma We should definitly start with "All files" if no local content. Otherwise I would keep having this open per default. To me that should be good enough fot his ticket. I think a discussion should be started if "All files" and "Local files" is a proper labelling (I think this is not really).

**Comment by adigitoleo** [comment] 2021-12-27 12:08
New user adding my 2c here: I expected the `Help > About kiwix > Learn more about kiwix` link to contain at least some information on where to get and how to add collections, and maybe some info on what the "Local kiwix server" button does. At the moment, new users just get sent back to the "advertisment" webpage which is probably where they downloaded the software from.

An explicit guide on how to generate a zim file for some small test website and add it would also be welcome.

**Comment by kelson42** [comment] 2023-08-11 18:12
@suterma At this stage basically a duplicate of #978 as other improvements have been implemented. Thank you again for your ticket!

**Closed by kelson42** 2023-08-11 18:12 UTC
Labels: enhancement, good first issue
