### ISSUE TITLE
Slow on the fly search

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#274] opened 2019-10-18 12:28 UTC
With kiwix-desktop_windows_x64_2.0-rc3, when you input search text in the search bar, there is an on the fly search feature which show the match list in a drop down list. But this feature is very slow for large file such as wikipedia_en_all_novid_2018-10.zim, so for the first few characters, the UI freeze for a while to fresh the on the fly match list.

It is not just slow with the first few characters. It seems to be slow for the second word, too.

Possible solutions: 
1. Speed up the process
2. Put a check box on the right. Default status is checked. Only on the fly search when checked. When change to cheched status , do search once too.

**Comment by kelson42** [comment] 2019-10-18 13:36
What kind of computer to you have? What is its CPU?

**Comment by wgt98** [comment] 2019-10-19 05:33
i7-3770 which I think could represent more than average performance even it is very old?

**Comment by wgt98** [comment] 2019-10-23 14:21
Being a consuming software instead of a production one, best to test it on entry level processors like Apollo Lake processors which is very slow to run production softwares but still gives instant experience for consuming ones like Chrome.

**Comment by kelson42** [comment] 2019-10-23 17:28
@wgt98 Im not sure what is exactly going on here. Want to make a new version of this ZIM file and let you test again.

**Comment by kelson42** [comment] 2020-01-28 16:00
I confirm the problem is still there with WPEN nopic recent and rc4.

**Comment by kelson42** [comment] 2020-04-09 10:41
@mgautierfr @jetownfeve21 To me, with 2.0, with WPEN FULL on my workstatin, the (suggestion) search is almost unusable at all.

**Comment by kelson42** [comment] 2020-04-24 10:29
I suspect to a large extend that if we fix #265, then it will be already a lot better

**Comment by kelson42** [comment] 2020-04-24 12:01
Closing this ticket in favour of #265.

**Closed by kelson42** 2020-04-24 12:01 UTC
Labels: bug, search
