### ISSUE TITLE
Closing the last tab unload the opened zim file

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#331] opened 2019-12-10 12:16 UTC
It should be kept open while closing the last tab.

**Comment by kelson42** [comment] 2019-12-10 13:49
@wgt98 What do you mean with "unload"? If no tab is open, nothing is open.

**Comment by wgt98** [comment] 2019-12-12 00:59
By unload I mean the zim file is unloaded since the search won't work anymore unless I open the file again.

**Comment by kelson42** [comment] 2019-12-12 14:36
@wgt98 This makes sense to me. Considering that Kiwix can have many ZIM files in its local library... with which ZIM file should the search run if there is no open tab?! This is more or less a duplicate of #315.

**Closed by kelson42** 2019-12-12 14:36 UTC
Labels: enhancement, question
