### ISSUE TITLE
Appimage fails to run on Ubuntu 21.10

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#745] opened 2021-12-14 11:09 UTC
**kiwix-desktop_x86_64_2.0.5.appimage** and **[kiwix-desktop_x86_64_2021-12-14.appimage](http://download.kiwix.org/nightly/)** doesn't start in **Ubuntu 21.10**:

```
name@test:~/Documents$ ./kiwix-desktop_x86_64_2.0.5.appimage
libGL error: MESA-LOADER: failed to open r600: /usr/lib/dri/r600_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Aborted (core dumped)
name@test:~/Documents$ [1:1:0100/000000.966299:ERROR:broker_posix.cc(41)] Invalid node channel message
Received signal 7 BUS_ADRERR 7ff5cdd66560
```

```
name@test:~/Documents$ ./kiwix-desktop_x86_64_2021-12-14.appimage
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: MESA-LOADER: failed to open r600: /usr/lib/dri/r600_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
Compiled with Qt Version  5.15.2
Runtime Qt Version  5.15.2
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Aborted (core dumped)
```

**Comment by Ubuntu-2020** [comment] 2021-12-18 11:03
I think this is problem in **Ubuntu 21.10** because **FreeCAD_0.19.AppImage** also did not start in **Ubuntu 21.10**:
```
 ./FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage
FreeCAD 0.19, Libs: 0.19R24291 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2021
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
libGL error: MESA-LOADER: failed to open r600: /usr/lib/dri/r600_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
/tmp/.mount_FreeCA6TQ1QL/AppRun: line 41:  2657 Aborted                 (core dumped) ${MAIN} "$@"
```

**Comment by ksbex** [comment] 2021-12-25 01:49
I"m getting a similar but slightly different error on Fedora 35.

```
$ kiwix-desktop_x86_64_2.0.5.appimage 
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_kiwix-4vlcKE/usr/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib64/dri/radeonsi_dri.so) (search paths /usr/lib64/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /tmp/.mount_kiwix-4vlcKE/usr/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib64/dri/swrast_dri.so) (search paths /usr/lib64/dri, suffix _dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Aborted (core dumped)
```

**Comment by kelson42** [comment] 2021-12-25 07:06
Duplicate of #393

**Comment by kelson42** [comment] 2021-12-25 07:16
Maybe related to #393

**Comment by mgautierfr** [comment] 2022-01-20 13:59
Confirmed on Fedora 35.
But the workaround forcing a mesa driver works :
`MESA_LOADER_DRIVER_OVERRIDE=i965 ./kiwix-desktop_x86_64_2022-01-20.appimage`

**Closed** 2022-03-03 09:47 UTC
Labels: bug, Linux, appimage
