### ISSUE TITLE
Flatpak warns about kiwix using an outdated runtime

### ISSUE THREAD

**Issue by VorpalBlade** [kiwix/kiwix-desktop#833] opened 2022-04-14 06:57 UTC
```console
$ flatpak update 
Looking for updates…
Info: org.kde.Platform//5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   org.kiwix.desktop
Nothing to do.
```

Presumably kiwix needs to be rebuilt against a newer runtime to fix this warning.

System info:
* Arch Linux (rolling release)
* Kiwix 2.2.1 (according to flatpak list)
* Flatpak 1.12.7

**Comment by kelson42** [comment] 2022-04-14 07:41
Yes, this is basically a duplicate of https://github.com/kiwix/kiwix-build/issues/526

**Closed** 2022-04-14 07:42 UTC
