### ISSUE TITLE
Wayland support!

### ISSUE THREAD

**Issue by iMonZ** [kiwix/kiwix-desktop#601] opened 2021-02-19 14:20 UTC
Kiwix-Desktop doesn't support native Wayland!

Here is the error that I get:

```

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

fish: “kiwix-desktop” terminated by signal SIGABRT (Abort)

```

Please add the Wayland support to this application! (QT already support native Wayland)

**Comment by kelson42** [comment] 2021-02-20 08:58
@iMonZ I believe if you compile Kiwix Desktop against Qt 5.11+ then you should have the Wayland support?! The binaries we provide should do so and there is a ticket for that, see https://github.com/kiwix/kiwix-build/issues/403. This ticket seems to be a duplicate of it.

**Comment by kelson42** [comment] 2021-07-15 05:46
We compile now against Latest Qt5, so it should work now with latest nightly http://download.kiwix.org/nightly/

**Closed by kelson42** 2021-07-15 05:46 UTC
Labels: bug, question

**Comment by iMonZ** [comment] 2021-07-15 07:29
> We compile now against Latest Qt5, so it should work now with latest nightly http://download.kiwix.org/nightly/. Please reopen if not.

Have someone tried it befor closing the issue?

**Comment by iMonZ** [comment] 2021-07-15 07:30
> We compile now against Latest Qt5, so it should work now with latest nightly http://download.kiwix.org/nightly/. Please reopen if not.

I think you need to add an Wayland modul

**Comment by iMonZ** [comment] 2021-07-19 09:50
> > We compile now against Latest Qt5, so it should work now with latest nightly http://download.kiwix.org/nightly/. Please reopen if not.
> 
> Have someone tried it befor closing the issue?

The flatpak version works fine now!
