### ISSUE TITLE
File size display is inaccurate

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#52] opened 2018-11-06 06:47 UTC
See image: Wikipedia is listed as 1 Gb and then when download starts it is now 9 Gb
![image](https://user-images.githubusercontent.com/21675885/48047367-1e093a80-e198-11e8-9a55-de1b4a8037a0.png)

**Comment by mgautierfr** [comment] 2018-11-12 15:45
Probably a duplicate of kiwix/kiwix-tools#237

**Closed by mgautierfr** 2018-11-12 15:45 UTC
Labels: bug
