### ISSUE TITLE
Can't view wikimooc2 video

### ISSUE THREAD

**Issue by Bam92** [kiwix/kiwix-desktop#101] opened 2019-01-25 12:52 UTC
Kiwix beta2
OS: Debian GNU/Linux
zim: https://download.kiwix.org/zim/other/wikimooc_fr_all_2018-06.zim

I can't read video of Wikimooc2, there's only sound. What's wrong?

**Comment by kelson42** [comment] 2019-01-27 07:40
Duplicate of https://github.com/kiwix/kiwix-desktop/issues/39

**Closed** 2019-01-27 07:40 UTC
Labels: bug, duplicate
