### ISSUE TITLE
How to read a ZIM file copied to a Usb key ?

### ISSUE THREAD

**Issue by LaurentFx** [kiwix/kiwix-desktop#582] opened 2021-01-25 12:50 UTC
Hello,

I installed the latest version of Kiwix, 2.0.5 on my computer running Windows 10 Pro,
then downloaded from the application, 2 Zim files: Wikipedia and Pokepedia.
Both files are working fine, I can browse the pages with Kiwix.
But, when I copy the folder containing the Zim files to a Usb key, Pokepedia no longer works (about:blank).
I tried to generate a new library.xml file with Kiwix-manage, with the path to Pokepedia, but it also doesn't work.

Thank you in advance for your response, best regards.

**Comment by kelson42** [comment] 2021-01-25 13:46
@LaurentFx Thank you for your bug report. Are you sure you have followed properly these instructions? https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)

**Comment by LaurentFx** [comment] 2021-01-25 14:08
Thank you for your answer.
I think I used kiwix-manage well.
I copied the zim file to a Usb key.
I opened a terminal, then went to the directory.
I ran kiwix-manage:
kiwix-manage library.xml add pokepedia_en_all_maxi_2019-05.zim
     
So, I got an error message:
Assertion failed at ../../SOURCE/libzim_release/src/file_reader.ccp:91 offset.v [0] <_size.v [0]

And the library.xml is empty.

Thank you in advance, best regards.

**Comment by kelson42** [comment] 2021-01-25 14:30
One problem seems clearly that with, kiwix-manage fails to add it to the library:
```
$ kiwix-manage library.xml add pokepedia_fr_all_maxi_2019-05.zim
$ more library.xml 
<library version="20110515" />
```

That seems to be a good reason why the file is not readable/visible on the USB flash drive.

**Comment by kelson42** [comment] 2021-01-25 14:34
@LaurentFx Are you sure you can read that file with Kiwix-Desktop? Because I can not.

**Comment by kelson42** [comment] 2021-01-25 14:44
@LaurentFx For some reasons pokepedia is not in the Zimfarm, I have created a new recipe and will compute a new update of the ZIM file. See https://farm.openzim.org/recipes. Hopefully with this newer file, it will work fine.

**Comment by LaurentFx** [comment] 2021-01-25 18:45
> One problem seems clearly that with, kiwix-manage fails to add it to the library:
> 
> ```
> $ kiwix-manage library.xml add pokepedia_fr_all_maxi_2019-05.zim
> $ more library.xml 
> <library version="20110515" />
> ```
> 
> That seems to be a good reason why the file is not readable/visible on the USB flash drive.

Thanks for your quick response and research.
kiwix-manage works with wikipedia.zim, but not with pokepedia.zim.
The problem could come from pokepedia.zim

**Comment by LaurentFx** [comment] 2021-01-25 18:52
> 
> 
> @LaurentFx Are you sure you can read that file with Kiwix-Desktop? Because I can not.

![Kiwix_bibliotheque](https://user-images.githubusercontent.com/77968960/105751228-04559880-5f46-11eb-90c5-6213e6db42a2.png)
![Kiwix_Pokepedia](https://user-images.githubusercontent.com/77968960/105751248-0a4b7980-5f46-11eb-894b-e125fc42783f.png)

Yes, I can read the pokepedia.zim file with kiwix-desktop.

I first downloaded pokepedia.zim from http://zim.pokepedia.fr, I could not read the file.

Then I downloaded pokepedia.zim from the kiwix-desktop library. This second file works with kiwix-desktop.

**Comment by LaurentFx** [comment] 2021-01-25 19:52
> 
> 
> @LaurentFx For some reasons pokepedia is not in the Zimfarm, I have created a new recipe and will compute a new update of the ZIM file. See https://farm.openzim.org/recipes/pokepedia_fr. Hopefully with this newer file, it will work fine.

Thank you.
I don't know the principle of Zimfarm.
If I understood correctly, you launched a request to create a new zim file, and in a few days the file will be available for download?

**Comment by kelson42** [comment] 2021-01-26 12:23
@LaurentFx Thx, it seems we have a regression with the development version, I have open a ticket here https://github.com/kiwix/kiwix-lib/issues/447.

**Comment by kelson42** [comment] 2021-01-26 12:55
@LaurentFx There is definitly something wrong with the latest Windows built of the Kiwix tools, see https://download.kiwix.org/zim/other/pokepedia_fr_all_nopic_2019-05.zim

**Comment by LaurentFx** [comment] 2021-01-26 13:10
> 
> 
> @LaurentFx Thx, it seems we have a regression with the development version, I have open a ticket here [kiwix/kiwix-lib#447](https://github.com/kiwix/kiwix-lib/issues/447).

Sorry for the inconvenience. Thanks for the work.
I was wondering, a problem with Zimfarm or Kiwix,
a problem with kiwix under windows, and pokepedia therefore.

**Comment by LaurentFx** [comment] 2021-01-26 13:12
> 
> 
> @LaurentFx There is definitly something wrong with the latest Windows built of the Kiwix tools, see https://download.kiwix.org/zim/other/pokepedia_fr_all_nopic_2019-05.zim

This is another version of Zim without images,
which works ? Thank you.

**Comment by LaurentFx** [comment] 2021-01-26 19:05
> 
> 
> @LaurentFx There is definitly something wrong with the latest Windows built of the Kiwix tools, see https://download.kiwix.org/zim/other/pokepedia_fr_all_nopic_2019-05.zim

I downloaded the zim file and tried adding it to library.xml, with kiwix-manage.
Unfortunately, kiwix-manage fails to add it to the library, the same assertion error appears:
assertion failed at ../../SOURCE/libzim_release/src/file_reader.ccp:91 offset.v [0] <_size.v [0]

Courage, thank you.

**Comment by kelson42** [comment] 2021-01-27 08:53
Thx, will come back to you there either when we get a newer ZIM file or the Windows bug is fixed. Hopefuly within two weeks. Thank you for your patience.

**Comment by LaurentFx** [comment] 2021-01-27 14:08
> 
> 
> Thx, will come back to you there either when we get a newer ZIM file or the Windows bug is fixed. Hopefuly within two weeks. Thank you for your patience.

Thank you for your post and the work.
It is not urgent, especially a fantasy to please my nephew, to install Pokepedia on his computer without an internet connection.
Thanks to Kiwix, courage for solving the problem.

**Comment by kelson42** [comment] 2021-01-27 19:40
@LaurentFx A new zim file has been prepared and is available at https://mirror.download.kiwix.org/zim/other/pokepedia_fr_all_maxi_2021-01.zim. Does that work better with this one?

**Comment by LaurentFx** [comment] 2021-01-28 13:22
> 
> 
> @LaurentFx A new zim file has been prepared and is available at https://mirror.download.kiwix.org/zim/other/pokepedia_fr_all_maxi_2021-01.zim. Does that work better with this one?

Thanks for the quick creation of the new Zim file.
I tested it, it works perfectly, and whatever directory contains the file.
There is no need to add the file with kiwix-manage, libray.xml updates itself.
And the updated file contains all the recent information.
Well done and thank you for the resolution.

**Comment by kelson42** [comment] 2021-01-28 14:09
@LaurentFx Great, I will close this ticket as the bug left is already tracked in an other ticket. Thank you again for reporting the problem and given the hints helping to fix it.

**Closed by kelson42** 2021-01-28 14:09 UTC
Labels: question

**Comment by LaurentFx** [comment] 2021-01-30 20:13
@kelson42 Thank you, reporting yes, advice, is overkill. You have completed all the resolution of the problem.
Courage with the other ticket, thank you for processing my request.
