### ISSUE TITLE
Kiwix-desktop dark-mode

### ISSUE THREAD

**Issue by macbeto** [kiwix/kiwix-desktop#873] opened 2022-08-17 16:42 UTC
Hi,
This is not an issue, just a question.
I have it installed in Linux Mint 20 and my qt5 setup is for dark mode interfeces, but I can't figure out how to put kiwix-desktop in dark mode.
Is there a way?

**Comment by kelson42** [comment] 2022-08-17 16:56
We don’t have a dark mode so far, see #320. This ticket is more or less a duplicate of it.

**Comment by Veeransh14** [comment] 2024-02-28 19:42
For this particular issue, i think firstly we have to add a checkbox, for the user to select for the dark mode or for the light mode and then define a function to handle the toggling of the dark and light mode (light mode is already there still we have to define both of them to classify them) and probably later we can adjust the dark scheme of the page/app.

**Comment by kelson42** [comment] 2024-05-22 17:58
Basically a duplicate of #318

**Closed by kelson42** 2024-05-22 17:58 UTC
Labels: question, UI, Qt
