### ISSUE TITLE
New appimage (2.0.1) is no more localised

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#427] opened 2020-04-24 11:18 UTC
Everything is in English, all the translation are missing (French for me).

**Comment by kelson42** [comment] 2020-04-24 12:18
Duplicate of #299

**Comment by kelson42** [comment] 2020-04-24 12:24
@jetownfeve21 I reopen the ticket as we might have lost here a few strings and that should not be the case. How to you check the localisation works, if the strings are not available in French?

**Closed** 2020-04-29 15:30 UTC
Labels: Linux, bug, duplicate, question
