### ISSUE TITLE
Cannot Open a ZIM File

### ISSUE THREAD

**Issue by ZhangBo1191** [kiwix/kiwix-desktop#24] opened 2018-08-14 14:43 UTC
Hello,I have got amaybe a bug on my laptop.
- windows version: 10.0.17134 Windows 10 Pro
- kiwix version: Kiwix 0.9

*when I want to cpen a ZIM,the Kiwix will close automatically.*

I try these solusion but the problem is still in there
- try another version ZIM file
- use Compatibility Mode

**Comment by ZhangBo1191** [comment] 2018-08-16 04:55
Now I download the  2.0 alpha version ,but I still can't load the ZIM file.
the zim file is wikipedia_zh_all_nopic_2018-07.zim
and the error code is 132
thank you

**Comment by kelson42** [comment] 2018-08-16 05:03
Kiwix 0.9 won't support these new ZIM files.
Kiwix 2.0 has still a but impacting big ZIM file reading on Windows. See #22. We will fix it soon.
I close that ticket basically because this is a duplicate of #22

**Closed by kelson42** 2018-08-16 05:03 UTC

**Comment by ZhangBo1191** [comment] 2018-08-16 05:05
but the zim file is only 8G
i think it is not so big

**Comment by kelson42** [comment] 2018-08-16 05:27
@ZhangBo1191 You are right, it not so big. In 10 days, if #22 is fixed and you still have the bug then we will have a look again, but quite sure this is the same bug.
