### ISSUE TITLE
Kiwix in Ubuntu Software Center

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#446] opened 2020-05-13 11:21 UTC
I think it would be nice if **Kiwix** will appears in **Ubuntu Software Center**.
What do you think?

**Comment by kelson42** [comment] 2020-05-13 11:26
Agree bu duplicate of #204

**Closed by kelson42** 2020-05-13 11:26 UTC

**Comment by mgautierfr** [comment] 2020-05-13 15:47
If Ubuntu Software Center support flathub, it is already the case.
