### ISSUE TITLE
Fonts Hard To See

### ISSUE THREAD

**Issue by tlmnot** [kiwix/kiwix-desktop#391] opened 2020-03-27 21:24 UTC
The fonts doesn't work well with manjaro thema.
![white-text-bug](https://user-images.githubusercontent.com/1029718/78167798-5e352100-744f-11ea-9471-b39bf0a39394.png)

**Comment by kelson42** [comment] 2020-03-27 21:26
Which version of Kiwix desktop? How have installed it?

**Comment by tlmnot** [comment] 2020-03-27 21:28
thats quick anyway i'm running 2.0-rc4 the lastest version.

**Comment by kelson42** [comment] 2020-03-28 05:37
@tlmnot How have you installed it? Via Flathub? Self-compiled? Via the appimage?

**Comment by tlmnot** [comment] 2020-03-28 07:03
Via appimage.

**Comment by kelson42** [comment] 2020-05-10 11:29
Seems to be a duplicate of #226 and there is a workaround.

**Closed by kelson42** 2020-05-10 11:29 UTC
Labels: bug, question
