### ISSUE TITLE
Unexpected crash when trying to open downloaded file (Win10)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#415] opened 2020-04-15 06:48 UTC
Steps to reproduce:
- Download a zim file from browser;
- Open zim from Kiwix-desktop;
- Application crashes.

**Comment by kelson42** [comment] 2020-04-15 06:55
I guess this is a duplicate of #403

**Closed by kelson42** 2020-04-15 06:55 UTC
Labels: bug
