### ISSUE TITLE
"Service workers not supported" error message when opening zimit-generated content

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#559] opened 2020-12-11 14:28 UTC
Tried generating a zim file from https://mesquartierschinois.wordpress.com, which yielded a 16Mb file. Tried to open it on Kiwix-Windows 2.0.5 and got the below error message.
The file can be read on android, but not on Kiwix-JS nor Kiwix-macOS

![101905438-c11eb080-3bb7-11eb-8079-add0a95f7b4d](https://user-images.githubusercontent.com/21675885/101914900-2f1da480-3bc5-11eb-822f-8ad74bf8911a.png)

**Comment by kelson42** [comment] 2020-12-11 14:29
Duplicate of #487

**Comment by Popolechien** [comment] 2020-12-11 14:31
@kelson42 Close ticket then?

**Closed** 2020-12-11 15:49 UTC
Labels: bug, duplicate, enhancement
