### ISSUE TITLE
Mouse Hover Tooltip in Kiwix as in Wikipedia

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#747] opened 2021-12-18 11:07 UTC
It will be good if the same tooltip appears in Kiwix as in Wikipedia when you hover over a link:
![Mouse-Hover-Tooltip](https://user-images.githubusercontent.com/65112331/146638777-e794f606-c98f-4acd-9333-4fd16afdc53d.gif)

**Comment by juuz0** [comment] 2021-12-18 11:10
Duplicate of https://github.com/kiwix/kiwix-desktop/issues/611

**Closed** 2021-12-18 11:40 UTC
Labels: duplicate, enhancement
