### ISSUE TITLE
Crash with WPRU on Windows

### ISSUE THREAD

**Issue by Diminon** [kiwix/kiwix-desktop#530] opened 2020-10-13 08:52 UTC
Crash when trying to open a particular zim

Kiwix Version: 2.0.4 Windows10 crashes when opening Wikipedia 30 GB 2020-10-07

**CPU=AMD A8-7680 Radeon R7, 10 Compute Cores 4C+6G 3.5 GHz
RAM=8GB
OS=Win10 x64**

_! Kiwix is installed on the second drive (not on the system one)_

**Drive C Win10 (SSD 128 GB Free 41,9 GB)
Drive D Kiwix+zim file (HDD, GPT, 3 TB Free 1,98 TB)**

**Comment by kelson42** [comment] 2020-10-13 08:55
@Diminon Do you have problem with other ZIM files on the same place? Do you have problem with a ZIM file on an other disk?

**Comment by Diminon** [comment] 2020-10-13 12:08
> @Diminon Do you have problem with other ZIM files on the same place? Do you have problem with a ZIM file on an other disk?

All zim-files are in one place, in one directory. All other zim-files work fine, zim-files size is from 135 KB to 591 MB. File Wikipedia 30 GB 2020-10-07 Pictures, Fulltext index offline version of Wikipedia in Russian downloaded from torrent.

**Comment by kelson42** [comment] 2020-11-18 06:13
@Diminon We have a new version of this ZIM file http://download.kiwix.org/zim/wikipedia/wikipedia_ru_all_maxi_2020-11.zim and a new version of kiwix desktop for windows. Would you be able please to update both and tell us if you still have the problem?

**Comment by kelson42** [comment] 2020-11-21 15:35
@Diminon Any feedback?

**Comment by kelson42** [comment] 2020-11-23 09:25
@Diminon Closing for the moment, please reopen if the problem is not solved on your end.

**Closed by kelson42** 2020-11-23 09:25 UTC
Labels: Windows, bug, question
